### ISSUE TITLE
Builtin jobs command missing -p flag

### ISSUE THREAD

**Issue by mil** [oilshell/oil#1017]
In `bash`/`dash`/`ash`, running `jobs -p` yields the pids of subshells. This is pretty helpful for scripting around with subshells (ex. killing all subshells with `kill $(jobs -p)`).

But currently in osh it seems like `-p` for jobs is unsupported.

In `osh`:
```sh
jobs -p
  jobs -p
       ^~
[ interactive ]:1: 'jobs' doesn't accept flag -p
```

**Comment by andychu** [comment]
Thanks for the report, I noticed this too.  I think this should be mostly a matter of looking through the jobs dictionary and printing PIDs from either Process or Pipeline (in `osh/builtin_process.py and `core/process.py`).  If you want to get familiar with Oil it could be a good one to take a stab at!  I can help

**Comment by mil** [comment]
Sounds good - i'll pick this up, will let you know if I get stuck.

**Comment by andychu** [comment]
Sounds good!   I just added the `-l` flag as a side effect of a previous bug (incomplete), and one thing to note is that all the flag defs are in a different file!  (I ended up doing it this way because in C++ we have to "compile" all the flag definitions)

So it should just be a one line change here, and then you'll have `arg.p`

https://github.com/oilshell/oil/blob/master/frontend/flag_def.py#L176

**Comment by andychu** [comment]
Thank you @glyh , this will be out with the next release 0.9.9

**Comment by jameschensmith** [comment]
@andychu, this should be safe to close now. `jobs -p` seems to work fine :slightly_smiling_face:

**Comment by andychu** [comment]
Yes thanks, forgot to close a couple weeks ago: https://www.oilshell.org/release/0.9.9/
