### ISSUE TITLE
Is there a formal grammar for oil language?

### ISSUE THREAD

**Issue by tailhook** [oilshell/oil#106]
Hi,

I came across this project and I like it very much. Especially great idea is that you can convert bash-like syntax into a modern and clean oil language. But I'm curious if I can write another implementation of the oil language.

The question as is standing in the title: is there a grammar for oil language in text form or maybe in programmatic form? I see osh (which is a bash subset, right?) language parser in the `osh/` directory but not the oil language. I'm probably missing something.

-----

My actual use case is following: I'm developing some containerization tools in rust and it would be very helpful to have a shell interpreter there. It must be in rust (as the tools) for two reasons: (1) for easier building and distribution, (2) to precisely control what script can and cannot do (i.e. I'm probably going to write a shell that runs privileged, but spawns processes in unprivileged containers).

**Comment by andychu** [comment]
Right now, only the OSH-to-Oil translator exists.  So the language mostly exists in my head, but it seems to be feasible based on that experiment.  There's no parser for it.

For container tools, I think it would make more sense to implement OSH in Rust.  In fact I wanted to kick that off as a "backup" for OPy.  I prefer OPy, but it is a weird way of doing things, so in case that doesn't work, maybe someone wants to implement OSH first.

I was going to start with the skeleton here, which is just algebraic data types that should translate easily to Rust:

https://github.com/oilshell/oil/blob/master/osh/osh.asdl

The lexer is already generated C code, so that can be used by Rust directly, which should save a huge amount of time vs. starting from scratch.

It's important to implement OSH before Oil, because otherwise we wouldn't know if the translation can be done automatically.  You could end up in a situation where you have a clean new language but it's very difficult or impossible to auto-translate.

**Comment by andychu** [comment]
I'm closing this since there isn't anything immediately actionable.  We could discuss it on #oil-discuss at oilshell.zulipchat.com if you have more to say.

I think formal grammars don't give you the properties that people tend to think.  For one, they don't specify the lexer.  There are a bunch of posts on my blog hinting at this.
