### ISSUE TITLE
"Magic" variables can't be used in first statement in script

### ISSUE THREAD

**Issue by BatmanAoD** [oilshell/oil#113]
It appears that the `SetSourceLocation()` function isn't called to initialize `LINENO` and `SOURCE_NAME` until the *second* statement in a shell script.

So, the following script prints an empty line:

    #!/usr/bin/env osh

    # print the line number
    echo $LINENO

While this one prints `4`:

    #!/usr/bin/env osh

    # print the line number
    : ; echo $LINENO

**Comment by andychu** [comment]
Thanks, confirmed.

**Comment by andychu** [comment]
@BatmanAoD Thanks for reporting this and sorry it took so long to fix!  It turned out to be something pretty silly, and reordering statements fixes it.  The `$LINENO` now matches bash exactly.

I am going to make another pass over the debug info, which includes:

- LINENO
- BASH_LINENO  (this is the CALL location, not the current execution location), BASH_SOURCE, FUNCNAME
- SOURCE_NAME -- which I made up myself.  I might get rid of this in favor of $BASH_SOURCE.

I should be able to fix #116 now; I know what's wrong there too.

-----

I'm working on making a "crash dump" for OSH.  I think this is a feature that might inspire people to use it over bash.  Basically if you hit an `errexit` failure or some other runtime error, it should give a Python-like stack trace, and also show you the state of the shell.

Very rough initial cut:

http://www.oilshell.org/share/osh-crash-dump.json

Shells have very little state, so this is pretty feasible!

**Comment by BatmanAoD** [comment]
Excellent! Thank you.

A crash-dump sounds excellent, but that gets me thinking about better error-handling in general for scripts.

One issue is that, as far as I know, `set -e` in Bash prevents capturing exit codes. (The only way I know of to capture an exit code is to assign `$?` to some variable immediately after running the command you're interested in.) If OSH provided a way to treat error code capture "specially" when `set -e` is in effect (the way Bash already treats `if <cmd>`), that would be fantastic.

A more generic feature would be to let users create scopes in which errors are not fatal *if* the user does something with the error code. I'm looking for inspiration to the [draft design for error-handling in Go 2][go2err], which introduces a `check` keyword to apply a pre-defined handler (much like a `trap`!) when an error is encountered in the `check`ed statement.

So, in scripting world, that would be something like:

    handle exitcode {
        if [[ $exitcode -eq 3 ]]; then
            echo "Got code 3!"
            # do some special handling here
        else
            echo "Didn't expect code $exitcode; exiting now"
            exit $exitcode
        fi
    }
    check {
        my_fallible_command
    }
    echo "If we get here, then we got exit code 0 or 3"

Note that Go also has a `defer` keyword that seems to be essentially synonymous with `trap <cleanup> EXIT`, except it permits multiple cleanup operations. This seems like it would be a nice feature as well.

  [go2err]: https://go.googlesource.com/proposal/+/master/design/go2draft-error-handling-overview.md

**Comment by andychu** [comment]
@BatmanAoD I made the same observation about Go 2 error handling here!

https://lobste.rs/s/evpjis/go_2_draft_designs#c_dmspjw

An interesting case of convergent thinking :)

I think this area needs to be explored, but the first thing I want to do is simply make `errexit` report the exit code and the command that failed!    Right now it's frustratingly silent.  Of course you could turn this off, but I really think the default should to be explain why the shell script stopped!

A hook for a custom error message would make sense.

It's not clear to me if any kind of more advanced error handling should go in OSH or Oil.  If there was infinite time, it would be both.  But I want to balance moving shell forward in a big way vs. piling more stuff onto a fragile and old system.

But I will keep this in mind for sure.  Error handling is a major area where shell needs to improve.
