### ISSUE TITLE
Redirecting output in a non-interactive shell doesn't always work in oil-native

### ISSUE THREAD

**Issue by jjbandit** [oilshell/oil#1188]
I believe this to be the root cause of a good number of the failures in the test suite.  It's difficult to say how many, but I've seen this (or a similar) bug in several tests now.

`./_bin/clang-dbg/osh_eval -c "type mapfile > tmp" ` -- doesn't work.  We get stdout in our shell instead of in the file `tmp`

`./_bin/clang-dbg/osh_eval -c "type fdasfds > tmp"  2>&1` -- works.
`./_bin/clang-dbg/osh_eval -c "echo 'hi' > tmp" ` -- works.
`./_bin/clang-dbg/osh_eval -c "(type mapfile) > tmp" ` -- works.

I originally thought maybe it was builtins only, but this works.

`./_bin/clang-dbg/osh_eval -c "[ fdas -gt foofdsa] > tmp 2>&1"` -- works

Actually, on closer inspection, I think it may be only `stdout` of builtins is broken.  The above command redirects stderr.

`./_bin/clang-dbg/osh_eval -c "alias thing=ding && alias > tmp 2>&1"` -- doesn't work .. and redirects `stdout`.

Any thoughts on this one @andychu

**Comment by andychu** [comment]
- First thought was that this is try/finally #1163 
- And second thought is YES, it definitely is because I see `sys.stdout.flush()` in the finally: block
  - so basically libc might print something into a buffer, and then the redirect is undone, and later the buffer is flushed.  So that will cause the symptom

I was wondering if we should not use libc buffered I/O like most shells?  Or if we should just do the flush() for now.

Let me think about it

**Comment by andychu** [comment]
i.e. I remember putting those `sys.stdout.flush()` into fix these kind of bugs, but maybe it's better if we don't need it at all ...

I think most of our output comes from `mylib.Stdout().write()` ... which is buffered CFileWriter using libc `fwrite()`.

I think shells tend to use the `write()` syscall directly

Although actually there is already an `fflush()` fix in that function?  Hmmm

**Comment by andychu** [comment]
So somehow  this may be an incomplete fix : https://github.com/oilshell/oil/blob/master/mycpp/mylib_leaky.cc#L420

**Comment by jjbandit** [comment]
Closed by #1200
