### ISSUE TITLE
`!!REF` in a regex does not work

### ISSUE THREAD

**Issue by Aloso** [oilshell/oil#1224]
I installed oil to try out its regex syntax. Unfortunately, I was not able to compile backreferences. When I type the following:

```
var r = / <"test" : name> !!REF name; %PCRE /
```

I get this error:

```
  var r = / <"test" : name> !!REF name; %PCRE /
                             ^
[ interactive ]:1: '!' isn't a character class
```

I also had the problem that `!!` was substituted with the last history entry, which I was only able to fix by leaving the shell, which deleted the history.

**Comment by andychu** [comment]
Thanks for trying it, and for the report!  I added an error message saying that it's not implemented with ERE.

So we actually don't have a PCRE or Python translator (both of which have backtracking constructs).  I was hoping someone would contribute those, but that didn't happen :-/

(The docs should probably be updated as well)

----

It's a good point that `!!` conflicts with shell history.  I'm not sure what to do about that right now.  I wanted all backtracking constructs to begin with the same modifier, so you can visually audit for backtracking (which can cause performance problems).

I noticed that you're the author of Pomsky/Rulex!   I just heard about it a month ago -- https://news.ycombinator.com/item?id=31694337

How long have you been working on it?

Eggex and Pomsky look very similar IMO, more similar than other projects at least.  (Eggex goes back to 2019, but I had another project "Annex" from 2014 or so.)

Although it looks like Pomsky uses `>> << !>> !<< ::1 ::name` for the backtracking constructs.

We should converge on a syntax if you agree that the backtracking should be called out :)  That's based on my experience with exponential time regex bugs.  (And I think RE2 and rust/regex won't execute many / most(?) of them.)

I wrote  about backtracking here (though not everyone understood this post, since it's more like a bunch of notes):  https://www.oilshell.org/blog/2020/07/eggex-theory.html

**Comment by andychu** [comment]
The history of `!!REF` is that it used to be `!REF`, and negation was `~d` for `\D`.   The `~` sort of makes sense because it's the complement of a set, and `~` is bitwise negation.

However `~` is also the Awk-like match operator, like

 `if (mystring ~ / d+ /)`

But that caused "stuttering" if you negated it:

`if (mystring ~ / ~d+ /)`

So I changed it to:

`if (mystring ~ / !d+ /)`

And changed `!REF` to `!!REF`.

----

However it's true that they ALL conflict slightly with shell history, because `!name` does history expansion.  Hm...

bash has special cases in history expansion to avoid the inherent conflict with lots of syntax like `${!ref}`.  So maybe the answer for Oil

- #452 
  - related: #710

**Comment by Aloso** [comment]
Hi @andychu,

thanks for clarifying. I just made [this comparison](https://pomsky-lang.org/docs/reference/comparison/) of different languages that are transpiled to regex. I'd appreciate it if you would check that all the information about Egg Expressions is correct, or if anything needs clarification, since I'm not very familiar with it.

> I was hoping someone would contribute those, but that didn't happen :-/

That's really unfortunate!

> I noticed that you're the author of Pomsky/Rulex! [...] How long have you been working on it?

Since February. I have a full-time job, so I work on Pomsky on weekends and sometimes on evenings.

> Eggex and Pomsky look very similar IMO

Yes, although I didn't know Eggex when I started work on Rulex. My main inspiration was Melody, which has a very different syntax.

> We should converge on a syntax if you agree that the backtracking should be called out :) That's based on my experience with exponential time regex bugs.

For now, I don't intend to change Pomsky's syntax for lookaround and backreferences. But I have planned a VS Code extension, which could show a warning when it detects that the expression might perform poorly.

> And I think RE2 and rust/regex won't execute many / most(?) of them.

The `regex` crate does not support lookaround or backreferences, since it compiles expressions to a finite state machine that doesn't backtrack. I believe the same is true for RE2.

**Comment by andychu** [comment]
The comparison page looks nice.  I would say:

- POSIX class: This is just `digit` -> `[[:digit:]]` in Eggex, and that works.
- non-capturing groups are just `()`, while capturing groups are `<>`.

My goal was for Eggex to support / be expandable to the union of all regex constructs.  But some things don't appear in ERE, like all the backtracking constructs, so I just reserved space for them.

----

BTW I talked with Aur Saraf @SonOfLilit  a few years ago about kleenexp , which looks active and has a comparison:

https://github.com/SonOfLilit/kleenexp#similar-works

**Comment by andychu** [comment]
Fix released: http://www.oilshell.org/release/0.12.0/

Thanks for trying Eggex, and let me know if you find any other problems!

**Comment by SonOfLilit** [comment]
Indeed active, I just released an alpha vscode extension that allows you to use if for search/replace in the editor (I'll release a version with much better UX once my vscode PR is accepted) :-)

vscode extension:
https://marketplace.visualstudio.com/items?itemName=sonoflilit.kleenexp

Online demo:
https://kleenexp.herokuapp.com/alice/kleenexp/
