### ISSUE TITLE
declare -i x=0

### ISSUE THREAD

**Issue by xyproto** [oilshell/oil#1251]
Hi,

I tried replacing these executables with a symlink to osh: `/usr/bin/bash`, `/usr/bin/sh`. (`/bin/sh` and `/bin/bash` are already symlinks into `/usr/bin` on Arch Linux).

This worked pretty well. The system rebooted and everything looked nice, until I tried running `extra-x86_64-build` from the `devtools` package, which in turn runs `makechrootpkg`.

The issue is that `declare -i ret=0` does not work under Oil / `osh`.

I tried comparing with `zsh` and `bash`, and `declare -i x=0` appears to be working under those.

This is a feature request to also add full support for `declare` under `osh`. Fully replacing `bash` with `osh` would be fun.

Thanks for creating Oil / `osh`!

**Comment by andychu** [comment]
Thanks for trying OSH, and for the report!  

In practice you can often remove `declare -i` and everything works fine -- i.e. people use it without knowing what it does.

Let me try to find this script and see how it's used.

----

For the cases where `declare -i`  is intended, unfortunately OSH doesn't support it for a pretty fundamental reason.


It enables dynamic parsing which is pretty unsafe and hard to reason about.  And you can do everything with `$(( ))`.

https://www.oilshell.org/release/0.12.0/doc/known-differences.html#values-are-tagged-with-types-not-cells

https://github.com/oilshell/oil/wiki/Language-Design-Principles

**Comment by andychu** [comment]
Ah OK I found it -- yeah in this case `-i` can simply be removed.  It's not used because `(( ret += 1 ))` already works just fine.


https://github.com/heftig/devtools/blob/master/makechrootpkg.in

Are you comfortable suggesting a patch, or would you prefer if I do?

----

I guess another thing is that we could make `-i` a no-op -- however that make break things in the rare case where you need it.

This would be a case where a lint tool would help #468

**Comment by andychu** [comment]
Hm I guess there's the argument that the OSH error doesn't tell you what is really wrong here

So if we make `-i` a no-op, then that script will work, and OTHER scripts MIGHT get a better error message.  I'll have to play with it

**Comment by andychu** [comment]
@happysalada I think you ran into `declare -i` in the Nix scripts?  Do you remember if you just removed `-i`, or if any changes were necessary?  

If you have a link to the diffs we can look through

It is possible you would need to change stuff like:

```
local -i foo
foo=i+1
```

to


```
foo=$((i + 1))
```

which is more like POSIX  anyway

**Comment by andychu** [comment]
There was also this November 2021 thread about it:

https://oilshell.zulipchat.com/#narrow/stream/121540-oil-discuss/topic/Why.20declare.20-i.20not.20supported

1. `-i` activates dynamic parsing and evaluation
2. you can always replace it with `$(( ))`
3. because we want to gracefully upgrade OSH to Oil, and Oil is Python/JS-like

But yeah I think it can still be a no-op

**Comment by happysalada** [comment]
I just removed `-i` previously. I'll keep in mind the suggested change, thank you!

**Comment by andychu** [comment]
I made `declare -i` a no-op:

https://www.oilshell.org/release/0.12.3/

Docs about it:

https://www.oilshell.org/release/0.12.3/doc/known-differences.html#values-are-tagged-with-types-not-locations-declare-i-a-a

https://www.oilshell.org/release/0.12.3/doc/shell-idioms.html#remove-dynamic-parsing

https://oilshell.zulipchat.com/#narrow/stream/325160-oil-discuss-public/topic/New.20docs.20for.20.60declare.20-i.60.20issue


Thanks for trying it, and let me know if you have other problems!
