### ISSUE TITLE
/ and % operators behave like Python and not bash

### ISSUE THREAD

**Issue by notwa** [oilshell/oil#1342]
this might not be a bug, but I've been searching the GitHub issues and oil's docs, and I haven't been able to come to a conclusion.

```sh
echo $((-3/2)) # -2 in oil, -1 in bash
echo $((3/-2)) # -2 in oil, -1 in bash
```

bash rounds towards zero, so oil is more like Python than bash in this regard. similarly, oil also adopts Python's modulo behavior:

```sh
echo $((-3%2)) # 1 in oil, -1 in bash
echo $((3%-2)) # -1 in oil, 1 in bash
```

I see that oil's expression language models Python, but this is an old-fashioned arithmetic expansion. should oil behave like bash (also dash, zsh) in this context?

**Comment by andychu** [comment]
Thank you, great point !!

I will look at this -- I think our C++ translation actually behaves like C/bash, but we should make these match for sure

Related to:

- #824 

because I think some arithmetic in C is defined by the compiler, like bit shifts.  And most shells just inherit it from C I think ?  Would be interesting to test

i.e. we are inheriting this from either C or Python but that's not the right thing to do

**Comment by andychu** [comment]
Fixed, thank you for testing!  https://www.oilshell.org/blog/2024/03/release-0.21.0.html
