### ISSUE TITLE
`break/continue N` out of nested loops yields unexpected behavior

### ISSUE THREAD

**Issue by alganet** [oilshell/oil#1459]
I searched to see if this issue had been previously reported but could not find anything, sorry if it is a duplicate!

### Test scenario:

```sh
counterA=100
counterB=100

while test "$counterA" -gt 0
do
    counterA=$((counterA - 1))
    while test "$counterB" -gt 0
    do
        counterB=$((counterB - 1))
        if test "$counterB" = 50
        then
            break 2
        fi
    done
done

echo "$counterA"
echo "$counterB"
```

### Expected output:

```
99
50
```
(tested on bash, busybox ash, busybox hush, dash, ksh, loksh, mksh, oksh, posh, yash, zsh) 

### Output on osh:

```
0
0
```
(versions tested: 0.8.12, 0.9.9, 0.10.1, 0.11.0, 0.12.9, 0.13.1)

### Explanation:

`break 2` should stop the outer `while` loop. This can be particularly troublesome if the inner breaks are responsible for stopping infinite loops.

**Comment by andychu** [comment]
Thanks for the report!  

Are you using this functionality in a script, or did you just notice the missing feature with testing?

I haven't implemented this because I haven't seen scripts that rely on it.   It's probably not too difficult, but I haven't thought about it that much

----

But at the very least we should not silently execute it incorrectly.  

And it's also not here, which is an issue: https://www.oilshell.org/release/latest/doc/known-differences.html

**Comment by andychu** [comment]
Oh no problem, actually I implemented this  a few weeks ago!  Will be out with the next release

**Comment by andychu** [comment]
Released -  https://www.oilshell.org/release/0.14.1/
