### ISSUE TITLE
YSH echo should allow multiple args

### ISSUE THREAD

**Issue by metov** [oilshell/oil#1605]
I'm sure there's a good reason for `simple_echo` but it escapes me. I never encounter issues with regular `echo` and `simple_echo` breaks a lot of useful tricks, like "prefix command with echo as a generic dry run" or `echo @ARGV` as a sanity check.

I like most of the rest of oil so I don't want to use osh. I just want to get rid of `simple_echo`. I know I can do `shopt --unset simple_echo` but it's tedious to put it in every script. Is there a way to globally unset this option? And for future reference, where is this documented and how would I go about finding it (if I wasn't asking here)?

**Comment by andychu** [comment]
Hm I'll take this as feedback

 As far as I remember, `simple_echo` was intended to eliminate the confusing behavior of

```
x=$'huge   string \n with spaces and newlines '
echo $x   # this splits the word, and then joins it by a single space
```

I think the reasoning it is for reduced since Oil doesn't do any word splitting.  So if you do

```
echo $x
```

the string won't be mangled.

----

I get the point about wanting to put `echo` before say `cp $x $y`

---

A related issue is that I think I want to get rid of `echo -e` and `echo -n` in Oil

- `echo -e`  can be done with real C-style strings, e.g.    echo $'\n'
- `echo -n $x` can be done with `write --end '' -- $x`

So then `echo` is consistent and doesn't have the problem where `x=-n` or `x=-e`

It can just take a list of words and output them separated by spaces, with NO options

If you want something more fancy, you use `write --sep 'x' --end '' -- $x $y $z` etc.


Thoughts?

**Comment by metov** [comment]
Is `$'` something that gets a lot of use? For example, https://stackoverflow.com/a/11966417 says it's bash specific and not familiar to most.

I never really got the purpose of `echo -e` and wouldn't miss it, but it would be nice if default behavior was `-e` not `-E`. Seems like usually you want `-e` and how often do you use `-E`?
 
`echo -n` seems like a reasonable thing OTOH. The `write` would work. So would `head` (if I understand you right):
```
$ echo hello | head -c -1 | wc
      0       1       5

$ echo -n hello | wc
      0       1       5
```

However, I just noticed that fish's echo just has a `--`. I suppose the reason to get rid of arguments is the issue where `echo $x`, instead of printing the content of `$x`, treats it as a a switch `-n`? `--` seems like a more natural way to deal with that, without having to give up arguments.

Incidentally, looks like zsh's echo doesn't mangle text either. Dunno how it works though.

**Comment by bar-g** [comment]
Doesn't `write one two` also kind of "mangle" by splitting the output into new lines?
How to echo a line without adding quotes?

If oil doesn't mangle space, nor word splitting, could multiple args be ok? just like with write? (can it distinuish argument from option?)

And for the legacy shell behavior, maybe have something like echo --singlespacedwords? or ...split?, maybe -s for short?

To convey that meaning maybe simple_echo could be called something like single_spaced_spit_echo?

**Comment by bar-g** [comment]
> How to echo a line without adding quotes?
> If oil doesn't mangle space, nor do word splitting, could multiple args be ok? just like with write? (can it distinuish argument from option?)

Maybe only allow multiple args if the first arg is `--`?

And for the old splitting and space-reducing line output behaviour?: `echo -- @a before @b followed       by @c`

**Comment by andychu** [comment]
Other options:

- Leave `echo` entirely alone; it's replaced with `write`, which does everything you want
- Add another builtin like `print` or `p` where `p $x` is like `write -- $x`


The reason I don't like those 2 options is that `echo $x` is familiar and easy to type :)  But it's subtly wrong in the rare case where `x` STARTS with `-e` or `-n`, and there's no way to  fix that, because `echo` doesn't accept `--`

**Comment by bar-g** [comment]
Your hint to "string language" examples was gold, could be very good info to show with error when ysh's echo is used wrongly.

Together with maybe naming it to "robust_echo",  rather than "simple_echo", it might be able to avoid quite some frustration. 

(It's really not simple if simple things like to echo a line stop working... ;-) of course like many shell things shooting ...towards own foot.

---
> [echo] can just take a list of words and output them separated by spaces, with NO options

if `echo -- foo bar => -- foo bar` could work in a "robust_echo", a good part of the confusion might also be gone together with the quoting requirement.

**Comment by bar-g** [comment]
Oh, now I saw #1117 (simple vs. strict), it had another "gold nugget" to for better understanding the "why this hurdle", and it also touched the naming.

I happily agree to "strict_echo", it's overall a better fit then my "robust_echo" suggestion.

And summarizing the parts that seemed to make it understandable to me:

The string requirement with shopt "strict_echo" prevents the implicit joining pittfall of the classic echo, as well as the pitfall of string parts getting parsed as arguments. Requiring a YSH string language makes everything explicit, including the escape/control character handling (string language examples here).

**Comment by bar-g** [comment]
> breaks a lot of useful tricks, like "prefix command with echo as a generic dry run"

Are there more tricks?
Might it be possible to somehow have a string language idiom to include a single/the remaining of the current line up to the next newline (`\n`)?

`echo \n'...`?
`echo n"...`?
`echo #'....`?

**Comment by bar-g** [comment]
`echo :'...`?
Might it fit because `:` seems to be a synonym of `true` it already "eats" everything behind ?

As in
`: echo not any more`

**Comment by bar-g** [comment]
Maybe  a separate command for a single line? `writeln`, `echoln`, `println`?

**Comment by bar-g** [comment]
Possibly good to allowing this?:
`writeln sleep $too_long_time => sleep 4096`
and this:
```
$ write one two
=>
one
two
```
nah, not yet what I wanted
```
$ writeln one two
=>
one two
```
ok

**Comment by bar-g** [comment]
>  j"\n", to indicate that it's like "\n" in a JSON string.

The j/JSON is only helpful to those already used to that. What does it do?
Does it allow escape sequences and replaces echo's -e option? So maybe is it an "escaped/escaping/escapable string"? `e"..."`

**Comment by bar-g** [comment]
And concerning `echo`. I don't see at the moment the reason why the strict_echo (in yzsh !) should not allow more than one string **if** after a `--`. (Everything after -- can be seen a one string then?)

Ok, an old `echo --` would just output an empty line if not changed into `echo -- --`, but isn't that kind of similar to other small "fix quoting" issues when upgrading to yzh?

Isn't the "single string" restriction needed only in osh to ensure robust code in other shells, but merely a nuisance in ysh?

**Comment by bar-g** [comment]
I think the remaining thing, which kept itching me all along, is the break or inconsistency in behaviour, going between `echo` and `write`:

```
~$echo writes...    singe lines
=>
writes... single lines
```
but
```
~$write writes...   separate lines
=>
writes...
separate
lines
```
Even if understanding the benefits of clean slate separatation of arg handling, could it make sense *not* to also change the default output format with `write`? Or, asked the other way, why would it make sense, to change the default output format? (say instead of `write` writing single lines, and maybe `writes` for multi-line output? Or `jot` and `write`?)

**Comment by bar-g** [comment]
Ups, sorry maybe the same answer: Because with separate lines by default, the output format is then a matter of the string language (quoting and optional split() )?

Could then be a very helpful note in the docs as well, for coming to grips with having `write` live aside from (strict) `echo`, and using both to their best fit.

**Comment by andychu** [comment]
Released a few weeks ago - https://www.oilshell.org/blog/2023/06/release-0.16.0.html

I would say `write` is what we would do if we're starting from scratch, and `echo` is just nice for familiarity

I view it as Go's `*p`, it's a concession to be familiar to C users
