### ISSUE TITLE
Initialization with rc files section of getting started doc references old filepath

### ISSUE THREAD

**Issue by pdebelak** [oilshell/oil#1687]
The [Initialization with rc files section](https://github.com/oilshell/oil/blob/12697216532eea6b04c98a5f59015372b8efd27a/doc/getting-started.md?plain=1#L52-L53) of the getting started doc references `~/.config/oil/oshrc` instead of `~/.config/oils/oshrc`.

**Comment by pdebelak** [comment]
I'm also noticing that doc says that osh will create an `osh_history` file in `~/.config/oils` but that doesn't appear to be true for me in version 0.17.0. It seems like `$HISTFILE` is set to `$PREFIX/share/oils/osh_history` - does that mean installation should be creating this directory, or should I be creating it myself? Also, the manpage for `osh` says it sources `~/.config/oil/oshrc`, but that is the old path.

**Comment by pdebelak** [comment]
I can confirm now that creating `$PREFIX/share/oils` lets `osh` create the `osh_history` file there. I set `PREFIX` to `$HOME/.local` on installation, so I'm not sure if something is off for custom prefixes, or that creating that directory should be documented, or that the installation step should create it.

**Comment by andychu** [comment]
Ah sorry, let me fix the typos ... Thanks for the reports

---

I did wonder about the setup issue ... Do distros usually make those directories for existing shells?  I didn't check

But we should probably provide some kind of script to do it, or maybe `./install.sh` should do it ...

I tried to follow the locations of `fish` from what I recall.  It uses the `share` dir for history too:

```
$ ls ~/.local/share/fish/fish_history 
/home/andy/.local/share/fish/fish_history

```

**Comment by andychu** [comment]
OK I just pushed a change to fix those typos and suggest making the other dir:

http://travis-ci.oilshell.org/github-jobs/4632/

If you go to `ovm-tarball` -> `docs` -> `Results`

you will get to

http://travis-ci.oilshell.org/github-jobs/4632/ovm-tarball.wwz/_release/VERSION/index.html

And then

http://travis-ci.oilshell.org/github-jobs/4632/ovm-tarball.wwz/_release/VERSION/doc/getting-started.html

(Although now I noticed I missed one Oil -> Oils ... will fix)

Let me know if you have other questions or problems, this is useful ...   It looks like I fixed one "oils" but neglected all the rest, in the last release

It's a little awkward because most people don't install shells themselves -- the distro does it.  But we want to nail this part down too

Also the Python/C++ is awkward now

**Comment by pdebelak** [comment]
I'm not able to find anything specific about how distros handle the histfile stuff, but I _think_ that they should always be scoped to the user, right? In that case, it seems like it should be safe to create `$XDG_DATA_HOME/oils` at runtime rather than build time, defaulting to `$HOME/.local/share/oils` if `$XDG_DATA_HOME` is not set.

**Comment by andychu** [comment]
Released, thanks for the reports!  https://www.oilshell.org/blog/2023/09/release-0.18.0.html
