### ISSUE TITLE
str slice out of range error in native version

### ISSUE THREAD

**Issue by Melkor333** [oilshell/oil#1775]
I encountered the following error:
```
ysh ysh-0.19.0$ = "ab"[2]
mycpp/gc_str.cc:107: BigStr *BigStr::at(int): assertion "i < len_" failed
Aborted
```

Is the intention to replace the assertion with something more useful?

**Comment by andychu** [comment]
Yes I noticed this bug in the C++ spec tests a few days ago:

[We're dow](http://travis-ci.oilshell.org/github-jobs/5708/cpp-spec.wwz/_tmp/spec/ysh-cpp/compare.html - we're down to a delta of 32, from 99 or so!

So yeah I think I will put this on `#help-wanted` because it's relatively focused.  It is a little tricky because it spans Python and C++, but it should be a small amount of code

**Comment by andychu** [comment]
to be clear, I'm not exactly sure what the problem is, but it should be relatively easy to track down, with a clear repro

**Comment by andychu** [comment]
Released -  https://www.oilshell.org/blog/2024/02/release-0.20.0.html
