### ISSUE TITLE
try { } should be the only form for simplicity

### ISSUE THREAD

**Issue by bar-g** [oilshell/oil#1785]
separated from https://github.com/oilshell/oil/issues/1784

Adding braces needed to make it find `const`.
```
ysh ysh-0.19.0$ try const c = {}

  try const c = {}
      ^~~~~
[ interactive ]:95: 'const' not found
ysh ysh-0.19.0$ 
```
```
ysh ysh-0.19.0$ try { const c = {} }
ysh ysh-0.19.0$ try { const c = {} }

  try { const c = {} }
              ^
[ interactive ]:96: fatal: Can't assign to readonly value 'c'
```

**Comment by bar-g** [comment]
Smells again like the (crystal) idea of parsing for passed blocks from left vs. right side mentioned in https://github.com/oilshell/oil/issues/1706

**Comment by bar-g** [comment]
Or, like dict vs. block braces, and `try` not triggering a restart of the parsing for the passed block, command, or expression (in the future)?

**Comment by andychu** [comment]
The error is sort of intended, because `try` can only be used with a command or block

```
try ls /tmp
try {
  ls /tmp
}
```

Something like `const c = {}` isn't parsed like a command -- it's parsed as an assignment statement because `const` is a **keyword**. This is fundamentally different than `ls`

---

However I ran into a related pitfall recently - https://oilshell.zulipchat.com/#narrow/stream/384942-language-design/topic/try.20pitfall.20in.20order.20of.20evaluation

I think we will make it even stricter, so the only valid forms are:


```
try {
  const c = {}
}
try {
  ls / tmp
}
```

So this is very consistent , if slightly longer

**Comment by andychu** [comment]
Released!  https://www.oilshell.org/blog/2024/03/release-0.21.0.html
