### ISSUE TITLE
`=` or `see` or `show` ...?

### ISSUE THREAD

**Issue by bar-g** [oilshell/oil#1788]
The `=` keyword really seems to stand out in ysh as a cryptic one that doesn't really tell what it does, and is also very similar to assignments and some operators.

It can seem as a bit too clever to think of assigning some value to the prompt and this then printing the result of an expression in a readable way.

Considering there is now `call`, maybe rename `=` to `print`, or `yield`, or ...?

**Comment by bar-g** [comment]
> print doesn't have the right connotation, because = is mainly used for debugging

Hm, and if we let it `see` expressions?

```
$ see null
(NoneType)   None
```

**Comment by bar-g** [comment]
Other connotation: to pour or spew an expression into the `see`... flowing away through the great stream of the terminal...

**Comment by andychu** [comment]
`see` is better, but I don't know of any language that uses it

If we follow the philosophy of "don't invent any new syntax", then `=` is the logical choice, because Lua has it

And Lua is a reasonably popular language (not as popular as Python or JS, but definitely up there)


If there is any other language that exists, that has the command/expression distinction, then I'd be interested in what it uses

But I don't think there is a good reason to invent something entirely new here

**Comment by andychu** [comment]
On the other side, `call` is already a special keyword (it used to be `_`), and we could also use a word now

As mentioned, arguably `call` could not be a keyword, and it could be `call (mylist->pop())`

But I dunno `call` and `=` seems reasonable to me.

(Also, we already changed this way too many times, and there are other things to polish!)

**Comment by bar-g** [comment]
Ok, so we'll see... ;-)

(Stange that nobody seems to have said `show`.)

**Comment by bar-g** [comment]
`see` seems taken
```
$ which see
/usr/bin/see
$ man see
RUN-MAILCAP(1)...
```
