### ISSUE TITLE
"Float" in J8 should probably be "Decimal"

### ISSUE THREAD

**Issue by l0b0** [oilshell/oil#1968]
IIUC, the [JSON number type](https://www.crockford.com/mckeeman.html) uses the `integer fraction exponent` format, which represents arbitrary-precision decimals. These in general don't map cleanly to any floating point representation, so the specification should probably be clear that these are decimal rather than floating point numbers.

**Comment by andychu** [comment]
JSON is a grammar, i.e. syntax-only -- it doesn't specify what types a given JSON message maps to

It fundamentally can't because Python, JavaScript, C++, etc. have different types

Oils behaves like Python -- `42` is mapped to an integer, while `42.1` is mapped to a float

(and I think Ruby probably has this behavior, maybe Raku, PHP, etc.)

**Comment by andychu** [comment]
i.e. J8 is like JSON and is logically separate from the interior types of Oils

It is valid to map J8 number syntax to a Decimal in some other programming language which supports Decimal

But Oils doesn't have Decimal

Maybe this can be clarified somewhere, not sure where.  maybe a FAQ

**Comment by andychu** [comment]
OK I added a FAQ in doc/j8-notation, thanks for the feedback
