### ISSUE TITLE
Source .profile on startup

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#248]
`bash` reads `~/.bash_profile`, `~/.bash_login`, and `~/.profile` as a login shell, or `.bashrc` when interactive and not a login shell, in that order (plus a lot of other stuff, see https://linux.die.net/man/1/bash under invocation for details).

I personally have a lot of scripts in `~/.profile` that I would like to see sourced automatically for my shell.

**Comment by andychu** [comment]
What happens when you source `~/.profile` with OSH right now?

For me, that doesn't work due to `bash-completion`  using some corners of the language that OSH doesn't implement.  Instead I source my (hopefully temporary) fork of bash-completion, described here:

https://github.com/oilshell/oil/wiki/How-To-Test-OSH

https://github.com/oilshell/bash-completion

This is one area where I don't want full compatibility with bash, because of this mess:

https://shreevatsa.wordpress.com/2008/03/30/zshbash-startup-files-loading-order-bashrc-zshrc-etc/

There is a very simple solutino that I use.  In `~/.config/oil/oshrc`, I simply do `source ~/.bashrc`.  Then everything is explicit and debuggable.

**Comment by jyn514** [comment]
I guess that's a reasonable alternative, but I think sourcing at least `.profile` would be nice. I keep my portable scrips in `.profile` and all the bash-specific stuff in `.bashrc` so bash-completion hasn't been an issue.

Everything in my `.profile` works with `osh` right now :)

**Comment by andychu** [comment]
OK, this has been documented in `help config` and I also added the rationale in osh-manual.md (which is rough and should be published somewhere.)

**Comment by andychu** [comment]
Typo on issue: that was #648
