### ISSUE TITLE
Prompt plugins shouldn't be able to set $? (also completion plugins, PS4, etc.)

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#268]
Expected behaviour:

```
$ not_found; echo $?
not_found: command not found
127
$ not_found
not_found: command not found
$ echo $?
127
```

Actual behaviour:

```
$ not_found; echo $?
osh error: 'not_found': No such file or directory
127
$ not_found
osh error: 'not_found': No such file or directory
$ echo $?
0
```

**Comment by jyn514** [comment]
Printing everytime `self.last_status` is modified is showing 6 updates after every command, including no-ops.

```
diff --git a/osh/state.py b/osh/state.py
index 8d0a9e7d..48bc4286 100644
--- a/osh/state.py
+++ b/osh/state.py
@@ -12,6 +12,7 @@ from __future__ import print_function
 
 import cStringIO
 import posix
+import sys
 
 from _devbuild.gen.id_kind_asdl import Id
 from _devbuild.gen.syntax_asdl import lhs_expr
@@ -462,7 +463,7 @@ class Mem(object):
     self.source_name = value.Str('')
     self.line_num = value.Str('')
 
-    self.last_status = 0  # Mutable public variable
+    self._last_status = 0  # Mutable public variable
     self.last_job_id = -1  # Uninitialized value mutable public variable
 
     # Done ONCE on initialization
@@ -472,6 +473,15 @@ class Mem(object):
     self._InitVarsFromEnv(environ)
     self.arena = arena
 
+  @property
+  def last_status(self):
+      return self._last_status
+
+  @last_status.setter
+  def last_status(self, value):
+      print(value, file=sys.stderr)
+      self._last_status = value
+
```

```
$ 
0
0
0
0
$ 
```

**Comment by andychu** [comment]
Hm I'm not able to reproduce this with the latest release or on master?

```
osh$ not_found; echo $?
osh error: 'not_found': No such file or directory
127
osh$ not_found
osh error: 'not_found': No such file or directory
osh$ echo $?
127
```

The fact that it gets set many times is probably due to the somewhat "functional" style that OSH uses... i.e. functions often return the status rather than merely setting it.  I have considered changing that, but I was afraid of it causing bugs.

bash has some unusual errexit behavior that we match (unless strict-errexit is set).  That is one of the more fragile parts of the codebase.

**Comment by jyn514** [comment]
I think I found the problem - I had `$(pwd)` in `PS1`. We should ignore the exit code from any commands in PS1, the same as bash.

**Comment by andychu** [comment]
Yes great catch!  This reminds me of another thing I've been meaning to explore:

- should prompts be able to change the state of the shell?  There are several constructs with side effects, like `${a=b}`, `$(( a++ ))`, or just `$( globalvar=value )`.
- should completion plugins be able to change the state of the shell?  

Both of those plugins have to be able to read the state of the shell, i.e. to display variables and so forth.  But it's not clear if they ever need to set variables, and what bash allows them to do.

It might be that `state.Mem()` needs a read-only interface ... I will look into fixing this.  Thanks for the report!

**Comment by andychu** [comment]
Update:

- bash has functions `{save,restore}_parser_state()` in `parse.y`, and they include the exit status and PIPESTATUS!  bash doesn't separate the parser from the runtime like OSH does.
- So PS1 and completion plugins can't mutate `$?`
- PS1 can't mutate global variables because its syntax implies that everything must be run in a
  subshell
- completion functions registered with `-F` CAN modify global variables.  In fact the completion API is designed so that it has to, because shell functions have no return values.

I don't like that the mutations from completion plugins persist.  But the only way around it is some kind of checkpoint/restore of `state.Mem`, and it might not be worth it right now.  It's not too hard but it's probably best to wait until it's in C++.

**Comment by andychu** [comment]
This fix is released!  Latest version of OSH: http://www.oilshell.org/release/0.6.pre20/
