### ISSUE TITLE
Quoted brackets aren't matched by % and # parameter expansion

### ISSUE THREAD

**Issue by Crestwave** [oilshell/oil#290]
$ var=[
    $ echo "${var#[}"
    
    $ echo "${var#"["}"
    [

**Comment by andychu** [comment]
Thanks for the report!  I'm not sure what's going on yet, but oddly bash behave differently than other shells here.

if var is `[foo]`, then

- dash gives `[foo]` and `foo]` for unquoted and quoted
- mksh gives the same thing
- zsh gives a "bad pattern error"
- bash gives `foo]` and `foo]`
- osh gives `foo]` and `[foo]`.  I will figure out something more reasonable; I suspect it has something to do with the fact that `[` is a glob metacharacter and it's unbalanced here.

**Comment by andychu** [comment]
OK I just fixed this. 

This case was pretty confusing!  dash, mksh, and zsh actually agree on a different behavior.

But bash and busybox ash agree, and that behavior seems to make more sense, so I made OSH agree with them.

Thanks for the report -- keep them coming!

**Comment by Crestwave** [comment]
> This case was pretty confusing! dash, mksh, and zsh actually agree on a different behavior.
> 
> But bash and busybox ash agree, and that behavior seems to make more sense, so I made OSH agree with them.

Don't all shells agree on the reported issue (`${var%"["}`)? There are inconsistencies when unquoted, as you mentioned, but OSH already behaved like Bash in that way.

> Thanks for the report -- keep them coming!

Seems that single quoted brackets still aren't matched; this also doesn't work on / expansion. Also, I forgot to mention a similar problem: `${var/[[]}` doesn't match. In this case, POSIX itself specifies that an opening bracket after the opening bracket in a regex match (opening opening bracket?) loses its special meaning. Also, strangely, it works in % and # parameter expansion; why do they behave differently? Conversely, the original issue didn't apply to / expansion.

**Comment by andychu** [comment]
Yes that's true, OSH already disagreed with dash/mksh/zsh.

I think the `[[]` issue you're talking about is known failing and covered here:

http://www.oilshell.org/release/0.6.pre18/test/spec.wwz/glob.html

I haven't decided what to do here yet, but I don't consider it high priority until a real and unpatchable script uses it.

`[[]` and `[]]` should really be written as `[\[]` and `[\]]`, which removes all the ambiguity.

The fundamental reason for the difference is long and old... basically OSH uses libc pattern matching like `glob()` and `fnmatch()`.  I don't implement my own globbing.

But ksh originated `% %% # ## and /`, and ksh is not written against libc's pattern matching.  It has its own engine with a different API.  Those constructs were basically designed with "not libc" in mind.

In order to implement `/`, you need the position of matches, analogous to `m.start(n)` and m.end(n)` in Python.  You don't need this for `% %%` etc.

So OSH compiles the `/` glob patterns to a regex, but it doesn't compile `%` glob patterns to regexes.   In that case it can just use `fnmatch()`.

So there are some inconsistencies there, particularly with regard to Unicode.  It may be worth opening another bug about this, but like I said I usually put them at high priority only when a "real" script tickles the behavior.  (This one seemed to be worth fixing simply because I was confused at the behavior, and it was a bug.)

**Comment by andychu** [comment]
Another possibility is to generate a runtime error for `${var/[[]}` rather than silently doing something non-POSIX... on the other hand, even recognizing to generate the error is probably hard.

**Comment by Crestwave** [comment]
Ah, that makes sense. Other issues I've noticed are with array subscripts in arithmetic expansion (e.g., single-quoted/escape ones aren't expanded, associative arrays expand to the associative array in JSON or something), as well as `"${var%"${var#?}"}"` where `var` contains an ANSI escape code yielding nothing.

> `[[]` and `[]]` should be written as `[\[]` and `[\]]`, which removes all the ambiguity.

Yes, this one I just stumbled upon interactively; I use `['[]']` in Bash scripts, although as I mentioned earlier, it's still broken in OSH. A single-quoted `-` also fails, and matching `['+-']` causes a fatal error.

I'm not sure what you consider a "real" script, but all of the issues I've reported have been from actual Bash programs, though not very practical ones, except for the one I mentioned. I tried to patch them, but there were too many issues.

I also tried an `sh` program, and encountered this issue and the problem with escape codes; I was only able to get it to work by patching it to use Bash features. I understand that these use more obscure features and aren't high priority, just want to let you know that they are used in some programs.

**Comment by andychu** [comment]
@Crestwave I don't recognize any of those bugs, except that I think the associative array issue may be fixed by #287.

I looked at the past issues you've filed and I don't see them.

Can you provide a repro for each one?  Like a short code snippet, what OSH does, and what you think should happen?

What I mean by "real" is something that people use, i.e. rather than a contrived test case.  You pointed to some on #274.

**Comment by andychu** [comment]
>  I use ['[]'] in Bash scripts, although as I mentioned earlier, it's still broken in OSH

In particular I don't recall this, and I am not even familiar with that syntax ... ?

**Comment by Crestwave** [comment]
> Can you provide a repro for each one? Like a short code snippet, what OSH does, and what you think should happen?

Sure. Escaped/single-quoted variables in array subscripts in arithmetic expansion don't expand:

```bash
$ i=0
$ arr[i]=0
$ (( ++arr['$i''] ))
Line 3 of '/home/user/.config/oil/oshrc'                                                             
  (( ++arr['$i'] ))
           ^
osh warning: Invalid integer constant '$i'
```

If you're wondering what use this has, it's usually done with associative arrays, as you have to use the `$` prefix for variables there and using it unescaped expands it twice, allowing code execution.

For completeness, associative arrays expand to JSON when expanded by arithmetic expressions (using `${arr[0]}` instead works):

```bash
$ declare -A arr
$ arr[0]=0
$ (( var = arr[0] ))
*** Error has no source location info ***
fatal: Expected array in index expression, got {'0': '0'}
```

Escape sequences are incorrectly handled when combining `%` and `#` parameter expansion:

```bash
$ var=$'\n'
$ printf %q "${var#?}"
''
$ printf %q "${var%''}"
''$'\n'
$ printf %q "${var%"${var#?}"}"
''
```

Single-quoted brackets aren't matched by parameter expansion:

```bash
$ var=[
$ echo "${var#'['}"
[
```

> In particular I don't recall this, and I am not even familiar with that syntax ... ?

It's simply single-quoted instead of double-quoted/escaped.

**Comment by andychu** [comment]
Thanks, these are good test cases!  I reproduced all of them as a difference between OSH and bash.  bash and mksh seem to agree on most of them, but not all.

Some of them may boil down to OSH's more static evaluation model, but I will think about them and either fix or document them after some hacking.

Let me create some new bugs to discuss them in isolation.

**Comment by andychu** [comment]
Reviewing the rest of the list you sent, I filed #294, that is indeed a bug.

The case

```
  (( ++arr['$i'] ))
```

is an intentional incompatibility, documented here:

https://github.com/oilshell/oil/blob/master/doc/osh-manual.md

http://www.oilshell.org/blog/2016/10/20.html

That can be written `++arr[i]`, `++arr[$i]`, or `++arr["$i"]` instead.

There may two related issues there: the undecidable parse issue, and also the recursive arithmetic evaluation rule #3, which is also intentionally not implemented.  Arithmetic expressions are only evaluated once unlike in ksh/bash.

**Comment by andychu** [comment]
This fix is released!  Latest version of OSH: http://www.oilshell.org/release/0.6.pre20/
