### ISSUE TITLE
Issues when using empty aliases with certain builtins

### ISSUE THREAD

**Issue by Crestwave** [oilshell/oil#299]
```bash
$ alias a=
$ a declare var=0 # Same result with local, but export works fine. This also fails when aliased to
   declare var=0
                 ^
[ expansion of alias 'a' ]:1: Invalid variable name ''
$ a (( var = 0 ))
  a (( var = 0 ))
    ^~
'/home/user/.config/oil/oshrc':13: Unexpected word while parsing command
line
$ a var=0
$ printf '%s\n' "$a"

$ a f() { :; }
  a f() { :; }
     ^
'/home/user/.config/oil/oshrc':16: Unexpected word while parsing command
line
$ a case a in a) : ;; esac
   case a in a
               ^
[ expansion of alias 'a' ]:1: Expected word type <Id_t Right_CasePat 94>, got <Id_t Word_Compound 199>
```

**Comment by andychu** [comment]
The inconsistency between export and declare/local will be fixed with #236 (dynamic assignments).

The other bugs are I guess because OSH has a different parsing/evaluation model of aliases.    They seem somewhat similar to cases 33-34 here:

http://www.oilshell.org/release/0.6.pre18/test/spec.wwz/alias.html

where I have alias LEFT='{' and alias LEFT='(', which works in most shells but not OSH.

That is basically because of the design philosophy here:

http://www.oilshell.org/blog/2019/02/07.html

I'm inclined to leave this as is, unless there it moves something here forward:

https://github.com/oilshell/oil/wiki/Shell-Programs-That-Run-Under-OSH

**Comment by andychu** [comment]
I just committed a spec test that records this incompatibility.  It's unfortunate that all shells do agree on this and OSH doesn't, but like I said, I'm going to put it low on the pile unless real world use cases show up.

I also started documenting some more of the known incompatibilities in doc/osh-manual.md.

**Comment by Crestwave** [comment]
> Are you using this for something? If not, I'm inclined to leave this as is, unless there it moves something here forward:
> 
> https://github.com/oilshell/oil/wiki/Shell-Programs-That-Run-Under-OSH

Nope; I found it while playing with https://github.com/rdebath/Brainfuck/blob/master/extras/bf2bash.sh, which is honestly quite horribly written/hacky in my opinion.

**Comment by andychu** [comment]
OK since I documented this incompatibility in the spec tests, I'm closing this... it may or may not come up again in the future :-/
