### ISSUE TITLE
No location info when sourcing ~

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#364]
I have this down to three characters! `. ~` gives `[??? no location ???] source '/home/joshua' failed: Is a directory`. It should look instead like this:

```
$ . ~
  . ~
  ^
[ interactive ]:13: source '/home/joshua' failed: Is a directory'

**Comment by andychu** [comment]
Ah I think this is because tilde detection is another pass, so the token location information gets lost?  Not sure exactly.

**Comment by jyn514** [comment]
Interesting, changing the tilde to /home/joshua brings back the location info:

```
. /home/joshua
  . /home/joshua
    ^~~~~~~~~~~~
[ interactive ]:2: source '/home/joshua' failed: Is a directory
```

**Comment by jyn514** [comment]
Looks like this might be happening in `osh/word.py`?

**Comment by andychu** [comment]
Yup, looks like this is a simple oversight... instead of returning `const.NO_INTEGER` for TildeSubPart, we can just return part.token.span_id.

I think the TildeSubPart used to be more complicated, but now it's very simple.  Every token has a span_id, and span_id is what we use to attribute location info.

Want to try changing that line and see what happens?  I think it should work.

**Comment by jyn514** [comment]
Yup that did it

**Comment by andychu** [comment]
Released: https://www.oilshell.org/release/0.7.pre1/
