### ISSUE TITLE
`set -x` looks weird for assignments

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#390]
Expected behavior:
```
$ set -x && A=1
+ A=1
```
Actual behavior:
```
$ set -x && A=1
+ (lvalue.LhsName name:A spids:[2650]) = (value.Str s:1)
```

**Comment by andychu** [comment]
This can be easily changed in `Tracer` in core/dev.py, now that I give it another look.

In `osh/string_ops.py`, we have `ShellQuoteOneLine` now, which I think is appropriate for the RHS, if it's a string.

Want to give it a try?

The LHS needs to be printed too though.   Not sure what bash does.  I guess what I want is for the representation to be unambiguous, since this is for debugging.  (The existing one pretty much is, but it's confusing.)

It's similar to the idea of Python's repr().

**Comment by andychu** [comment]
This was fixed awhile ago, feedback welcome
