### ISSUE TITLE
Frozen pyconfig.h causes compile error on FreeBSD

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#410]
```
$ curl https://www.oilshell.org/download/oil-0.6.0.tar.xz > oil.tar.xz
$ tar -xf oil.tar.xz
$ cd oil-*
$ ./configure
$ gmake
// lots of warnings
../native/posixmodules.c:1418:17: error: too few arguments to function call, expected 2, have 0
    if (setpgrp() < 0)

/usr/include/unistd.h:572:1: note: 'setpgrp' declared here
int setpgrp(pid_t, pid_t);  /* obsoleted by setpgid() */
^
```

**Comment by jyn514** [comment]
I'd fix this myself but I'm not sure how to build a release tarball.

**Comment by jyn514** [comment]
Looks like this is an error with configure, because there's a version of it right above with both arguments:
```
#ifdef SETPGRP_HAVE_ARG
    if (setpgrp(0, 0) < 0)
#else /* SETPGRP_HAVE_ARG */
    if (setpgrp() < 0)
#endif /* SETPGRP_HAVE_ARG */
```

**Comment by jyn514** [comment]
It looks like the configure script for python checks for this, maybe there's a way to get that information without having to rewrite the code for it? If there's only a few things we need to check that might not be worth it.

Python-2.7.13/configure, line 11688:
```
for ac_func in setpgrp
do :
  ac_fn_c_check_func "$LINENO" "setpgrp" "ac_cv_func_setpgrp"
if test "x$ac_cv_func_setpgrp" = xyes; then :
  cat >>confdefs.h <<_ACEOF
#define HAVE_SETPGRP 1
_ACEOF
 cat confdefs.h - <<_ACEOF >conftest.$ac_ext
/* end confdefs.h.  */
#include <unistd.h>
int
main ()
{
setpgrp(0,0);
  ;
  return 0;
}
_ACEOF
if ac_fn_c_try_compile "$LINENO"; then :

$as_echo "#define SETPGRP_HAVE_ARG 1" >>confdefs.h

fi
```

**Comment by jyn514** [comment]
Ok never mind this is an issue with the release process. `./configure` is run for Python-2.7 before OSH is distributed, but it needs to be run afterwards. Take this error for example:

```
/usr/bin/ld: error: undefined symbol: ftime
>>> referenced by timemodule.c
```

This seems to be happening because `HAVE_FTIME` is always defined to true in `pyconfig.h`, but it's _not_ true on every platform, FreeBSD for instance. End users need to run autoconf to generate pyconfig.h themselves in order to be portable.

Alternatively, we could try removing things that aren't present on every platform, but I have a feeling that's going to be a game of whack-a-mole that we'll never really find all the bugs for. Even if it works for every platform we try, someone will want to come along and run on a platform we haven't. I think it makes sense to use the existing work done by the Python developers to make this architecture independent.

**Comment by andychu** [comment]
Right this has to do with the how I stripped down CPython.  I just froze the `pyconfig.h` from an Alpine Linux run :)

The theory is that a shell is only relies on the POSIX kernel interface.  It doesn't rely on Linux or OS X or FreeBSD.  A shell is a very old program that only makes like 20 syscalls, and shouldn't require ANY #ifdefs or much in the way of a `configure` script.  Linux, OS X, and FreeBSD should all be POSIX compatible enough.

That being said, let me look at this specific error ...

Of course CPython has lots of #ifdefs because it exposes a ton of functionality beyond POSIX.  But that is not true of a shell.  The only other dependency of a shell besides `libc` is GNU readline, and that is optional.

**Comment by jyn514** [comment]
This specific error seems to be a function that was removed in posix 2008: http://man7.org/linux/man-pages/man3/ftime.3.html

**Comment by jyn514** [comment]
I see what you're saying, but I'm not sure it makes sense to have a configure step if you're going to run configure on a machine other than the one you compile on.

**Comment by andychu** [comment]
We have our own hand-written `configure` script in the root of the repo.  The frozen thing should go away over time.  

That's part of this work: http://www.oilshell.org/blog/2018/11/15.html    .  It's not done yet but I can see the light at the end of the tunnel.  `native/posixmodule.c` is a step on the way there (it's 7K lines smaller than what's in `Python-2.7.../Modules/posixmodule.c`.

----

It looks like `gettimeofday()` should work on any POSIX system to implement `time.time()`.  So I just pushed a change that got rid of the `ftime()` fallback.  I

For the pgrp thing, we're not using that function in Oil, but I kept it in `native/posixmodule.c` because I thought we might need it for job control.

We could simply delete that function if we don't need it.  I'm pretty sure that everything in the shell can be implemented portably.

----

BTW I also just documented `devtools/release.sh quick-oil-tarball` on the Contributing page.  That's what I'm using now to make a tarball on Linux, and then copy it to OS X for testing.

If Oil builds on Linux and OS X without any #ifdefs, then I'm pretty sure it will also build on FreeBSD the same way.  The Python interpreter has all sorts of #ifdefs we don't need.

**Comment by andychu** [comment]
Yeah after that change, it seems like `time.time()` works fine.  I did:

```
make clean-repo
make _bin/oil.ovm-dbg  # because this is faster than _bin/oil.ovm
_bin/osh-dbg -c 'time sleep 1`
```

(I could also have made a tarball, but that is the quick way to test it in the tree.  Yes the build system is complicated!!!  There are bugs so it's best to `clean` often when testing this kind of stuff.)

So HAVE_FTIME is just portability crud from Python we don't need.

**Comment by andychu** [comment]
OK I pushed another change that should address the `pgrp`  problems.

After reading the man page, I see that that is also portability crud.  I didn't realize that those functions have newer portable versions.  We don't use them in Oil so they don't need bindings in `posixmodule.c`.  Python is older so it has all this stuff.

I can make a tarball later and test it on  OS X.  It should be closer to compiling on BSD.

This is good -- the code is getting smaller, as intended :)

**Comment by jyn514** [comment]
It's closer to compiling but it segfaults in some of the tests :( The way I testing this originally is with the tarball, but since the tarball won't build until the tests pass, I can't tell if your changes work. I'll keep you updated.

**Comment by andychu** [comment]
Are you trying to build the tarball on FreeBSD?  The way I test on OS X is to build the tarball on Linux, and then copy it over there.

----

BTW `build/prepare.sh configure` has a different purpose (yes the build system is complicated).  We don't distribute its output.  `pyconfig.h` was frozen once, and has had manual changes since then:

https://github.com/oilshell/oil/commits/master/Python-2.7.13/pyconfig.h

**Comment by jyn514** [comment]
I am, yes. That's probably one of the reasons I was running into so many issues. It's mostly working except for the tests, now, though

**Comment by andychu** [comment]
BTW this is related to #167 .  The spec tests are worth running on OS X, FreeBSD, etc.  But I've never done that.

We should port those somehow (they depend on bash, coreutils, Python 2).

In contrast I don't think the unit tests aren't very important to run on other platforms.

**Comment by jyn514** [comment]
This was just the tests for `native/libc.c`. The spec tests are probably worth porting as well, but I'm just trying to get a minimum build running.

**Comment by jyn514** [comment]
Ok I can compile on BSD! The libc tests still segfault but I can work on that another day.
