### ISSUE TITLE
Feature request: `[ -n ]` should return 1

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#440]
From `help test` in bash: `      -n STRING      True if string is not empty`.
It's not documented, but `[ -n ]` is true in bash, osh, sh, mksh, and zsh.
This is particularly damning since `[ -n $SOME_VAR ]` will expand to `[ -n ]` when SOME_VAR is empty and not quoted.

For user-friendliness, it would be nice for `[ -n ]` to return false instead.
Not sure what impact this has on compatibility, but anyone with [ -n $SOME_VAR ] already has broken behavior anyway (since it will always be true).

**Comment by andychu** [comment]
I wrote about this problem here:

http://www.oilshell.org/blog/2017/08/31.html

Not sure it's worth reading -- it will probably just give you a headache.

But the real solution here is the Oil language.  It will probably just be `if (some_var) { ... }` like in Python.

`[ -n $unquoted ]` is definitely a pitfall, but it's documented and consistent in other shells.  It's just broken by design, hence the new language ...

**Comment by andychu** [comment]
To summarize, `[ -n ]` is just like `[ foo ]`, a test for whether the string `-n` is non-empty.  This is one of many places where shell has a confusion between code  and data.  You're thinking of `-n` as an operator (code), but it's actually data.

**Comment by jyn514** [comment]
That's ... very confusing. Closing since this is required by the standard but that's a giant pitfall :(
