### ISSUE TITLE
Illegal syntax is caught during execution, not parsing

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#462]
Consider the following script:

```sh
sleep 1
if true
        echo hi
fi
```

If run with osh, osh will wait a second before giving an error: `osh.sh:4: Expected word type <Id_t KW_Then 214>, got <Id_t KW_Fi 213>`

It would be better to give the error up front; in my case, the lines before this took about 2 minutes to run.

**Comment by jyn514** [comment]
For comparison, all other shells also wait a second before giving the error.

**Comment by andychu** [comment]
Yeah OSH used to detect this error up front, but it changed last year.  Implementing `alias` correctly *requires* that it parse one statement at a time.

However the error can still be detected with `osh -n`.

-----

It would be possible to add a mode that disables aliases and does it the old way.  Parsing everything up front was always my intention for the Oil language, if not OSH.  But now Oil is more of an upgrade to OSH.

One issue is that I put parsing options under the global execution options, e.g.

`shopt -s parse-at`

Instead of

`# __syntax__ parse-at    # new syntax, note this whole line must be a comment`

I could still add that, but it wasn't entirely straightforward due to all the places the parser is called recursively.

----

Although another bug here is that the error message is unfriendly in exposing internal names.

**Comment by andychu** [comment]
I think this is working as intended, because you can catch the error with `osh -n myscript`

So parsing can be all at once, but with `osh myscript` it behaves like existing shells
