### ISSUE TITLE
If oil is an upgrade to bash, why is it's license downgraded to allow denying freedom to its users?

### ISSUE THREAD

**Issue by ian-kelling** [oilshell/oil#525]
https://www.gnu.org/licenses/copyleft.html
https://www.gnu.org/philosophy/why-copyleft.en.html

I prefer to use and contribute to gplv3+ programs because otherwise they tend to be used by others as part of software or devices which restrict their users freedom to run, copy, distribute, study, change and improve it. This is an injustice https://www.gnu.org/proprietary/proprietary.en.html that oil's Apache2 license allows and Bash's GPLv3+ doesn't, which seems like a major difference and downgrade to me. The project should mention this when comparing to Bash.

**Comment by andychu** [comment]
I've considered "same license as bash" in the past, on the feeling that I don't really want anyone to use Oil just because it has a more permissive license than bash.  [1]

However Oil is actually more like a derivative work of **Python**, not bash.  There are currently over 100K lines of CPython code in Oil.  While I want to reduce that, it's not going to be zero for a long time.

So basically out of respect to the developers who wrote that code, I want to offer them essentially the same terms when using my code combined with their code.

Also I tend to take a more practical view.  I realize there is a large ideological difference.  But the practical difference is small.

If I were to get a bunch of good contributions from companies due to GPL, that would be a practical difference.  But that basically never happens.  I worked on the toybox project which has very direct experience with this:

http://landley.net/toybox/faq.html

I expect this will come up later and I can write something about it.  But right now the priority is to get the project working in a technical sense, not argue about licensing.  If the project doesn't work, then the license doesn't matter.


[1] Note: that's not necessarily my current feeling -- I also think building more things with / on top of Oil regardless of license is a reasonable goal.
