### ISSUE TITLE
BASH_SOURCE should be referencable as string (virtualenv)

### ISSUE THREAD

**Issue by dflock** [oilshell/oil#581]
[Virtualenv](https://virtualenv.pypa.io/en/latest/) doesn't work. You can create a virtualenv, but the activate script throws an error:

```
osh$ source bin/ac      if [[ $BASH_SOURCE == */* ]]; then
            ^~~~~~~~~~~~
/usr/share/bash-completion/bash_completion:2043: Array 'BASH_SOURCE' can't be referred to as a scalar (without @ or *)
^C
osh$ ^C
osh$ source bin/activate
  if [ "${BASH_SOURCE-}" = "$0" ]; then
        ^~
bin/activate:5: fatal: Array 'BASH_SOURCE' can't be referred to as a scalar (without @ or *)
osh$ 
```

This is using Virtualenv version 16.7.9

**Comment by andychu** [comment]
OK thanks for the report.  I see that here

https://github.com/pypa/virtualenv/blob/master/virtualenv_embedded/activate.sh

but weirdly  my virtualenvs work.  I created them with `python3 -m venv`

**Comment by andychu** [comment]
OK, I added a special case for BASH_SOURCE since I've seen that a lot, including in other places besides virtualenv.  

This is a very useful report, thank you!  Weirdly it's not in my own virtualenvs.

If you want to test it out before I release, it's pretty easy to make a dev build on most Linux distros (Debian, Ubuntu, Arch, etc.).

https://github.com/oilshell/oil/wiki/Contributing

Basically run a few code generators and then `bin/osh` will be the latest version.

**Comment by andychu** [comment]
Released with https://www.oilshell.org/release/0.7.0/
