### ISSUE TITLE
zsh syntax hidden behind conditionals prevents running certain scripts with Oil (Run enhancd)

### ISSUE THREAD

**Issue by danyspin97** [oilshell/oil#624]
https://github.com/b4b4r07/enhancd

Error received:
```
      ENHANCD_ROOT="${${(%):-%x}:A:h}"
                       ^
/home/danyspin97/.local/share/enhancd/init.sh:28: Expected } to close ${
```

**Comment by andychu** [comment]
Hm I think that's zsh syntax?  That doesn't appear to be valid bash.

But the project does say it supports bash.

**Comment by DanySpin97** [comment]
Sourcing init.sh in bash does not show any error.

**Comment by andychu** [comment]
Ah this is because it's a bash and zsh script in one :-(  This is a side effect of static parsing.

https://github.com/b4b4r07/enhancd/blob/master/init.sh#L28

I ran into this with `git-completion` too -- it has some small zsh snippets within a huge bash script hidden behind conditionals.


`shopt -s parse_zsh` might be one solution ... it could accept zsh syntax but not run it ... gah.

**Comment by DanySpin97** [comment]
> Ah this is because it's a bash and zsh script in one

Ah, I could have never thought it would exists something like this. I guess, too much flexibility leads to weirds things.

**Comment by andychu** [comment]
We now parse this ! 

https://www.oilshell.org/blog/2024/06/release-0.22.0.html
