### ISSUE TITLE
Functions missing from test/unit.sh

### ISSUE THREAD

**Issue by dtwilliamson** [oilshell/oil#63]
The functions `one` and `smoke` as documented in https://github.com/oilshell/oil/wiki/Contributing and in the comments in `test/unit.sh` are missing from that script.

**Comment by andychu** [comment]
Ah sorry I renamed the function, so I just updated the wiki page.  As an example, this should work:

    $ test/unit.sh unit osh/lex_test.py 
 
For unit tests, you can also just run

    oil$ export PYTHONPATH=.
    oil$ osh/lex_test.py
     ... (13 tests pass)

`test/spec.sh smoke` should work -- let me know if it doesn't.  It's in a different file.

`test/spec.sh all` can be a little flaky because it runs a ton of tests in parallel, which depend on your environment.  Fixing that is issue #42.

But `test/unit.sh all` should work, and running individual spec tests should work.  You can get a list by doing `ls spec/*.test.sh`.

To run `spec/func.test.sh`, do:

    $ test/spec.sh func

The wrapper determines which shells to run it with, and how many allowed failures there are.

Let me know if you have more questions!

**Comment by andychu** [comment]
I'm cleaning up issues for the next release, so closing this... feel free to reopen if you need more help.

0.4.alpha1 release is here: http://www.oilshell.org/releases.html
