### ISSUE TITLE
Install on Ubuntu 16.04.3 - python 3 set as the default python breaks install script

### ISSUE THREAD

**Issue by mdamien** [oilshell/oil#64]
To be specific, it's in `build/quick_ref.py`, `#!/usr/bin/env python` should be `#!/usr/bin/env python2`

This change may be needed on other files, as you wish.

Also, on a related note, when running `build/dev.sh minimal`, `libc.so` is linked to `_devbuild/py-ext/x86_64/libc.so` but the generated file is `_devbuild/py-ext/x86_64/libc.cpython-35m-x86_64-linux-gnu.so`. Thus raise an Import Error in `native/libc_test.py` when doing `import libc`.

And....on a still related note, when I get the correct libc.so import, I'm getting:

```console
native/libc.c:287:3: warning: implicit declaration of function ‘Py_InitModule’ [-Wimplicit-function-declaration]
   Py_InitModule("libc", methods);
   ^
```

I'm investigating, maybe it would be useful to setup a Travis to show the working chain.

**Comment by andychu** [comment]
Yeah there's basically only one other person besides me working on it right now, so unfortunately the environment is pretty specific -- it's a vanilla Ubuntu 16.04 image.  I'm not sure why you would want python -> python3, as that will break a lot of stuff besides OSH.

It might be a good idea to set up something like Travis, but if that were the case it would have python -> python2 since that's the default on Ubuntu.

Issue #42 is related.  I do want to specify the test environment better, which is related to the build environment, but so far it hasn't been a priority.

Some other people have changed all the shebang lines and then not contributed anything else, so honestly I'm not too excited about that as a first change :-/

**Comment by mdamien** [comment]
I agree.

> I'm not sure why you would want python -> python3, as that will break a lot of stuff besides OSH.

/usr/bin/python is set as an alias for python3 for [archlinux since 2010](https://www.archlinux.org/news/python-is-now-python-3/) and the latest Ubuntu LTS too, so I guess it kinds of makes sense for a lot of people.

And yes, not gonna do that as a PR :+1:
