### ISSUE TITLE
Syntax check of dynamic rvalue names in arithmetic expressions (ble.sh)

### ISSUE THREAD

**Issue by akinomyoga** [oilshell/oil#644]
> In Issue #620
>
> I added some failing test cases for dynamic assignment here inspired by ble.sh:

While testing ble.sh, I noticed that Oil does not produce syntax errors for `((${prefix}var))`, but it actually fails to evaluate at runtime. (Or does this construct `((${prefix}var))` have a different usage in Oil?) The added test cases 8fdb25d do not contain this kind of the case where the dynamic variables are referenced as *rvalue*.

```console
$ bin/osh -n -c 'echo $((${prefix}var))'
(C {<echo>}
  {
    (word_part.ArithSub
      anode: (arith_expr.ArithWord w:{(${ Id.VSub_Name prefix) <Id.Lit_ArithVarLike var>})
    )
  }
)
$ bin/osh -c 'ble_var=123; prefix=ble_; echo $((${prefix}var))'
  ble_var=123; prefix=ble_; echo $((${prefix}var))
                                    ^~
[ -c flag ]:1: warning: Invalid integer constant 'ble_var'
0
$
```

**Comment by andychu** [comment]
Yes this is intentional, same issue as #648 and #645.  Arithmetic is never recursively evaluated, both because it's confusing and because of the security issue.

This is sort of philosophically related, and has the Fedora security links at the end too:

http://www.oilshell.org/release/latest/doc/simple-word-eval.html

**Comment by andychu** [comment]
Let's talk about them all on #648 if you like
