### ISSUE TITLE
 declare -A dict=() not allowed in Oil

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#661]
> Also what's the difference between declare -A dict and declare -A dict=() in bash?

There are three different states for variables in Bash. In addition, the "set" state can be categorized into two sub-states:

1. Not declared (slot is not allocated)
2. Declared but unset (slot is allocated, but no value is set)
3. Set (slot is allocated, and a value is set)
   1. Empty
   2. Non-empty

See the following test case for the behavior differences:

```bash
# test5.sh

function is-declared() { declare -p "$1" &>/dev/null; }
function is-enumerated-by-declare() { declare | grep -q "^$1="; }
function is-enumerated-by-varname-expansion() { eval "printf '%s\n' \"\${!$1@}\"" | grep -q "^$1\$"; }
function is-enumerated-by-compgen () { compgen -v | grep -q "^$1\$"; }
function is-enumerated-by-compgen-arrayvar () { compgen -A arrayvar | grep -q "^$1\$"; }
function show-status {
  local -a msg=(yes)
  local f
  for f in $(compgen -A function -- is-); do
    "$f" "$1"
    echo "$f: ${msg[$?]:-no}"
  done
}

echo "[undeclared]"
show-status dict
echo "[declared]"
declare -A dict
show-status dict
echo "[set]"
dict=()
show-status dict
```

```console
$ bash test5.sh
[undeclared]
is-declared: no
is-enumerated-by-compgen: no
is-enumerated-by-compgen-arrayvar: no
is-enumerated-by-declare: no
is-enumerated-by-varname-expansion: no
[declared]
is-declared: yes
is-enumerated-by-compgen: no
is-enumerated-by-compgen-arrayvar: no
is-enumerated-by-declare: no
is-enumerated-by-varname-expansion: no
[set]
is-declared: yes
is-enumerated-by-compgen: yes
is-enumerated-by-compgen-arrayvar: yes
is-enumerated-by-declare: yes
is-enumerated-by-varname-expansion: yes
```

Related to this, in the help-bash mailing list, I have heard about some script library that gives a default array content when the definition is not given by the application. I'm not sure if it is a good design, but in that library, the empty array is one of the possible configurations, so one needs to distinguish *the unset state* (`declare -A dict`) from *the empty state* (`declare -A dict=()`). Also, if the array is associative, the library wants to declare the associative array attribute in advance. Such a script can be achieved in the following way:

```bash
# library
declare -A dict
is-array-set() { compgen -A arrayvar -X "!$1" -- "$1" &>/dev/null; }

function initialize-lib {
  if ! is-array-set dict; then
    # default dictionary
    dict=([left]=right [up]=down)
  fi
}


# application

# ... set up dict here ...

initialize-lib
```

_Originally posted by @akinomyoga in https://github.com/oilshell/oil/issues/653#issuecomment-599193601_

**Comment by andychu** [comment]
@akinomyoga Let's talk about this issue here since it's one of the high priority ones.

Question:  Is it sufficient to make `declare -A dict=()` **identical** to `declare -A dict` in Oil?

If so, I think that should be possible.

This kind of hidden state is avoided in Oil ** by design**.  If that's the only way you can detect the state, I call that a bash implementation detail!  (And probably an accident to be honest)

```
is-array-set() { compgen -A arrayvar -X "!$1" -- "$1" &>/dev/null; }
```

**Comment by akinomyoga** [comment]
Thank you!

> Question: Is it sufficient to make `declare -A dict=()` identical to `declare -A dict in Oil`?

Yes. It's sufficient for `ble.sh` (but of course I don't know about the other scripts, so I cannot ensure that there are no problems at all).

> This hidden third state is avoided in Oil by design.

But it seems Oil has already the unset state and the empty state for scalar variables, and hidden differences between two unset states, the declared and the undeclared. Is it a bug or a deprecated feature? If it is the design, why does it allow the third state for normal variables and disallow for arrays?

```bash
$ osh -c 'declare -r null empty=; echo "undef: ${undef+set}, null: ${null+set}, empty: ${empty+set}"'
undef: , null: , empty: set
$ osh -c 'declare -r null; undef=1; null=1'
  declare -r null empty=; undef=1; null=1
                                   ^~~~~
[ -c flag ]:1: fatal: Can't assign to readonly value 'null'
```

I think the problem of Bash is that `${name+set}` cannot be used for array testing because it is equivalent to `${name[0]+set}` in Bash. In Oil, `${name}` doesn't mean `${name[0]}` except for special variables `FUNCNAME`, `BASH_LINENO`, and `BASH_SOURCE`, so maybe there is another option to support `${name+set}` for checking the set state of arrays.

----

By the way, people usually use the following implementation for `is-array-set` (although it is still *a non-trivial hack*). The above trick by `compgen` is just used in `ble.sh` because it doesn't involve costly `fork`.

```bash
is-array-set() { [[ $(declare -p "$1") == *=* ]]; }
```

----

> Another instance of bash's confusion over its own state is that in bash 4.3 and below set -u made the use of empty arrays like a=() illegal. It was confusing empty and unset, but that was fixed in a later version.

Oh, I didn't know that. Thank you!

```bash
$ bash-4.3 -c 'set -u; arr=(); echo X${arr[@]}'
bash-4.3: arr[@]: unbound variable
$ bash-4.4 -c 'set -u; arr=(); echo X${arr[@]}'
X
```

**Comment by andychu** [comment]
OK I think it should be relatively easy to make `declare -A dict=()` a synonym for `declare -A dict`.

I do want to have a strong common subset of bash and Oil (which is significantly different than supporting every last bash feature.)

But for curiosity, can you point me to a place in `ble.sh` where writing the latter will cause a bug, and writing `=()` fixes the bug?  I am having trouble seeing it.  Where does the program notice the difference?

----------

Oil doesn't have three states, it has:

- Undef (`echo $zzzundefined`)
- string which may or may not be empty
- array which may or may not be empty
- assoc array which may or may not be empty

The model is basically something like this:

```
struct cell { bool readonly; bool exported; bool nameref; value val }

value = Undef | Str(...) | MaybeStrArray(...) | AssocArray(...)  
```

I'm pretty pleased with that model because it can run many bash scripts, but it appears to be a significant simplification of bash's model.  bash's data model is very confusing to me.

There are lots of confusing behaviors if you do something like

```
declare -a array=(['key']=value)  # note this is -a not -A
```

https://www.oilshell.org/release/0.8.pre2/doc/known-differences.html#indexed-and-associative-arrays-are-distinct

**Comment by andychu** [comment]
So to be more specific:

```
declare -r null   # this gives you the Undef value with readonly == true
declare -r empty=  # this gives you the Str('') value with readonly == true
echo $undef   # this evalutes to `Undef`, which is treated differently depending on set -u
```

Does that make sense?  This model has held up pretty well over time.

One thing I don't like is that `bool exported` only applies to strings.  However I just have to write some if statements in the code to support that.  But it would be nicer if the data structures corresponded to the invariants of the interpreter.

**Comment by andychu** [comment]
Actually I added the `repr` builtin to let you see the data model.  Let me know what you think:

```

osh$ s=
osh$ a=()
osh$ A=(['k']=v)

osh$ repr s a A

s = (cell exported:F readonly:F nameref:F val:(value.Str s:''))
a = (cell exported:F readonly:F nameref:F val:(value.MaybeStrArray))
A = (cell exported:F readonly:F nameref:F val:(value.AssocArray d:{'k': 'v'}))

osh$ declare -r A=(['k2']=v2)
$ repr A
A = (cell exported:F readonly:T nameref:F val:(value.AssocArray d:{'k2': 'v2'}))

```

**Comment by andychu** [comment]
Ah OK this snippet shows the difference in bash.  You can have `-A` and be unset at the same time.

In Oil you can be `Undef`  OR you can be the empty associative array (which is not unset).  Does that make sense? 

```
declare -A unset                                                                                                                                                                                                                              
declare -A empty=()                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
echo len=${#unset[@]}                                                                                                                                                                                                                         
echo len=${#empty[@]}                                                                                                                                                                                                                         
                                                                                                                                                                                                                                              
set -u                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                              
echo len=${#unset[@]}                                                                                                                                                                                                                         
echo len=${#empty[@]}                                                                                                                                                                                                                             
```


So yes I see why you want to write `A=()`.  But I don't think the combination of `-A` and unset is useful.

It's very similar to the confusion between empty arrays and unset values in bash 4.3.  What kind of  
programming language would not let you use empty arrays?!

**Comment by akinomyoga** [comment]
> But for curiosity, can you point me to a place in ble.sh where writing the latter will cause a bug, and writing =() fixes the bug?

This is a good question! Probably there are no real problems in `ble.sh` caused by this difference. At least, I haven't noticed any so far. The reason why I want to initialize associative arrays in Bash is that I don't want to have the unset state which may cause confusion and unintended behavior. The philosophy is the same with Oil, but the difference is that `ble.sh` has to live inside the Bash world, i.e., cannot change the Bash behavior. Here, "*everything should be initialized soon*" is somewhat the way of `ble.sh` to organize the Bash world. I don't want to make an exception for this strategy just for Oil which `ble.sh` doesn't target now.

Actually, it's for normal arrays but not for associative arrays, but there was a problem caused by uninitialized arrays in `ble.sh`. Since then, I always explicitly initialize empty arrays in the declare command.

Anyway I could rewrite the command to be `declare -A dict; dict=()`, but I don't see any reason to force users to write in the second way. When a user wants to declare an empty associative array, the first way the user will try must be `declare -A dict=()` but not `declare -A dict; dict=()`. For this reason, I guessed `declare -A dict=()` will be supported by Oil in the near future. Under this assumption I don't want to unnecessarily change many places in the codes to `declare -A dict; dict=()` and then change back to `declare -A dict=()` again. Also, I assumed that it is easy to support this, which is the reason why I marked this with double stars.

> Oil doesn't have three states, it has:
>
> (snip)
>
> The stack is list of frames, each of which is a dictionary of string -> cell.

It appears to me that the internal model is similar for Bash and Oil, but just Bash has some weird interface. Bash also has only two states in the cell, *set* and *unset*, in this context. But there is another state in the *dictionary*, i.e., the cell *exists* or *not*. When the variable name is not registered in the dictionary, it is what I called *the undeclared state* above. When the variable name is registered in the dictionary, and the cell state is unset (`Undef`), it is *the unset state*. When the variable is registered in the dictionary and has a value, it is *the set state*. The only internal model difference seems to be that Bash has the type information in the cell instead of in the value.

Those three states are just corresponding to `undefined`, `null`, and `{}` in JavaScript, respectively. Or, undefined variable (runtime error), `None`, and `{}`, respectively in Python, respectively. Or, undeclared pointer (compile error), `nullptr`, and `new std::unordered_map<...>` for a pointer to a dictionary in C++, respectively. Many languages have similar three states for variables and its values.

I agree that the interface of Bash is terrible, i.e., full of accidental features and *post hoc* designs which are not user-friendly at all, but `ble.sh` is a resident of such a world...

> ```
> declare -r null   # this gives you the Undef value with readonly == true
> declare -r empty=  # this gives you the Str('') value with readonly == true
> echo $undef   # this evalutes to `Undef`, which is treated differently depending on set -u
> ```
> Does that make sense?

OK! I understand now! `Undef` can be `readonly`. Also, non-existent variables return `Undef` even if it doesn't have own `cell`. `declare -p` in Oil only succeeds when it has non-`Undef` values. It fails for variables that exist but have `Undef` values.

**Comment by akinomyoga** [comment]
> Actually OSH has the repr builtin to let you see the data model. Let me know what you think:

Thank you for letting me know the useful builtin!

And with `repr` builtin I found that `declare -A dict; dict=()` won't work as I expected. It turns into a normal array.

```bash
osh$ declare -A dict
osh$ repr dict
dict = (cell exported:F readonly:F nameref:F val:(value.AssocArray d:{}))
osh$ dict=()
osh$ repr dict
dict = (cell exported:F readonly:F nameref:F val:(value.MaybeStrArray))
osh$
```

**Comment by andychu** [comment]
Hm that's a good point.  It's a bit tricky and I'll have to test that case.  

Right now in OSH the LHS and RHS are independent like in Python.  In Python you have `{}` and `[]` for empty dict and array.

But I guess OSH will have to look at the LHS to see if `()` means dict or array.  That is a bit confusing...

```
declare -A x
x=()   # empty dict
declare -a y
y=()  # empty array
```

So basically the meaning of `z=()` depends on some hidden state?

**Comment by andychu** [comment]
I was thinking it might be a good idea to accept `declare -A A=()` for compatibility, but also come up with a distinct RHS syntax.

Although that already exists because in Oil you can use `var`:

```
var A = {}
```

**Comment by andychu** [comment]
There is some precedent for that... I think I will allow `declare -A A=()` to make sure that it's **set** in bash.

But you can't do `A=()` if A is associative because that would be "changing the type".

If you want to change the type, you have to `unset A` first and that will work in bash, following the "common subset" principle.



```
$ A=()
$ declare -A A=([k]=v)
-bash: A: cannot convert indexed to associative array
```

**Comment by akinomyoga** [comment]
The problem is that `()` is a natural guess of the empty associative array literal from the non-empty ones `(['key']=value)`, which conflicts with the natural guess for the empty array from `(value)`. I don't know if you like it, but another option is to assign a special type to `()` (inspired by C++ initializer list).

```bash
(['key']=value) # AssocArray
(value)         # MaybeStrArray
()              # EmptyInitializer
```

The rule is as follows: When an EmptyInitializer is assigned to an array variable, it initializes the array to be empty. When an EmptyInitializer is assigned to an associative array, it initializes the associative array to be empty. Otherwise, it creates a new empty instance of MaybeStrArray and replaces the existing value.

**Comment by andychu** [comment]
@akinomyoga I added a special case when the context is clear.

`a=()` still means empty indexed array.  I didn't want to look at the LHS to determine the RHS (even though there's one other case where we do that for bash compatibility).  Even if you call it `EmptyInitializer`, it's still a funny semantic.

----

I documented it here, let me know what you think:

https://github.com/oilshell/oil/blob/master/doc/quirks.md

https://github.com/oilshell/oil/blob/master/doc/known-differences.md#values-are-tagged-with-types-not-cells

**Comment by andychu** [comment]
Also I documented the "common subset principle" here which was the rationale for this change:

https://github.com/oilshell/oil/wiki/Language-Design-Principles

**Comment by akinomyoga** [comment]
OK, thank you! `EmptyInitializer` was just a possibility. The decision is understandable.

----

By the way, the above *Language Design Principles* page says `2>&-` (I think `2>&1-` is typo) will not be supported. In that case, is there any other way to close the file descriptor? According to the *Common Subset Principle*, there should be a way of *trivial modification*.

> We won't add more stuff like  ${x@P), ${x^^}, cat <<< 'hi', or exec 2>&1-

**Comment by andychu** [comment]
I edited the page to be more clear: we **will** support those constructs, but we won't add **more syntax** that looks like that.  

The new syntax will look more like Python or JavaScript, etc.

Related: http://www.oilshell.org/blog/2017/08/12.html

**Comment by andychu** [comment]
(Also feel free to edit the wiki if you see any problems.  Those pages are all editable.  You can start a thread on Zulip if you're unsure about a change.)

**Comment by akinomyoga** [comment]
OK, thank you!

## Q. How to clear an outer-scope associative array?

I noticed another problem for the current design of `arr=()`. Currently, I'm thinking of how to clear an associative array declared at an outer scope but have not yet found a simple solution in Bash other than `dict=()`. See the following case.

```bash
f2() {
  # What is the alternative of the following. How to clear dict in f1 here?
  # dict=()

  # 1. declare -A dict=() doesn't work because it creates a new local variable in f2.
  # 2. declare -gA dict=() doesn't work because the array to clear is not the global one.
  # 3. unset -v 'dict[@]' doesn't work because it removes the array rather than clears it.
  # 4. The only way is the following manual clears of all entries, which is not a simple modification.
  for key in "${!dict[@]}"; do
    unset -v "dict[$key]"
  done
}

f1() {
  local -A dict=()
  dict['a']=b
  dict['c']=c
  f2
}

local -a dict=(1 2 3)
f1
```

**Comment by andychu** [comment]
OK, well after thinking about it, I don't think the workaround is that bad especially because it can be encapsulated into a function, like `unset-outer-dict dict`.

I think there are other things in #653 that will help more, and then maybe we can revisit this if it's still an issue.

There is a stdlib dir for shell snippets, but not sure it's worth putting there (and it doesn't do anything yet)

https://github.com/oilshell/oil/tree/master/stdlib

I also changed the principle to say "small modification" not "trivial modification".  I would call using the function small but maybe not trivial.

https://github.com/oilshell/oil/wiki/Language-Design-Principles

**Comment by akinomyoga** [comment]
OK! Thank you!

**Comment by andychu** [comment]
Fixed: http://www.oilshell.org/blog/2020/03/release-0.8.pre3.html
