### ISSUE TITLE
enforce upper limit on hard-coded file  descriptors

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#674]
@akinomyoga On second thought I think there are a couple reasons to cap the max file descriptor that a **program** can mention (not that the shell can use):

1. Oil is fine because it uses `fd_state.Open()` which does the right bookkeeping to prevent collisions.  But other libraries in the same process may not be able to use Oil's internal data structures.  They might implement their OWN bookkeeping, but then they need a range, which I suggest is > 100.

I suggest these ranges:

- 0 to 9:  POSIX shell scripts can mention these
- 10 to 99 : scripts that run under bash like ble.sh can mention these
- 100+ : if no scripts mention these, then libraries linked within the shell process can do their own bookkeeping above this range.

2. The second reason is that it makes shell scripts more portable in theory.   `exec 123456789 >& 1` may or may not work depending on the kernel the shell script is running on.

```
$ cat /proc/sys/fs/file-max 
2448569
```

**Comment by andychu** [comment]
Complication:

 I guess a program can write `exec {fd} <& file.txt` a thousand times and use up all descriptors.  Then Oil is still fine, but the library can't assume that it can use FDs greater than 100.

But it's also possible to add an additional check that a program doesn't leave more than 100 descriptors open at a time... even if it does NOT mention `exec 101 <& file.txt`

Hm...

**Comment by akinomyoga** [comment]
OK, this is a difficult issue.

> They might implement their OWN bookkeeping, but then they need a range, which I suggest is > 100.

> - 100+ : if no scripts mention these, then libraries linked within the shell process can do their own bookkeeping above this range.

It seems to me it is non-trivial how to force external libraries to use 100+ file descriptors. Unless that library is written in shell scripts, Fortran or other archaic languages, it is likely to use `open`, `dup`, `fcntl`, etc. or more high-level `fopen`, etc. which correspond to the shell construct `{fd}<>` and doesn't manage their own bookkeeping. There is no need for bookkeeping because such libraries are always using this strategy `{fd}<>`. The complicated bookkeeping is only needed when one wants to do nasty things like `INT<>`.

Maybe one way is to open all 3-9 or 3-99 file descriptors for reservation at the startup time of Oil before loading other libraries. In this way, the other library will never use the file descriptor in this range as they use `{fd}<>` strategy. Then, when a shell script explicitly requests the usage of the file descriptor in this range by `INT<>`, Oil can release the reserved file descriptor for the shell script. This seems like a good idea except that it may easily touch the upper limit of the file descriptor numbers in the process/system...

**Comment by andychu** [comment]
Hm on thinking again I think that there has to be a reserved range even for the simplest of cases.  Consider

```
# main.sh
source troublemaker.sh  # I must have at least one FD open to do this, call it FDX
```

```
# troublemaker.sh

# FDX for 'source' has to be open for this whole time

# I am enumerating every file descriptor and writing something to it, hoping to cause a problem
for i in $(seq 1 $(cat /proc/sys/file-max)); do
  exec {fd}< foo.txt  # open for reading on a new FD
  read foo <& $fd  # mess you up
done

# FDX is still open
```

I guess every shell would be messed up by something like this.  You don't even need `exec {fd}< foo.txt`.  You can just do `echo foo >& $i` probably.

But still I like it better if there is a distinction between the user program and the interpreter/any in-process libraries.

**Comment by akinomyoga** [comment]
> ```bash
> # troublemaker.sh
> 
> ...
> ```
> I guess every shell would be messed up by something like this.

It's just caused by the wrong manipulation of file descriptors. The trouble arises just because it forgets to close the file descriptor by `exec {fd}>&-`. If the script is written in the proper way, opening many files would not cause trouble. But, if the script is intended to cause trouble, we cannot anyway prevent it since there are many other ways to cause various types of trouble.

----

> - max descriptor a shell script can mention explicitly, e.g. exec 99>& 1
> - max descriptor that {fd}< can use.
>
> Those are both easy to implement, and unlikely to break anything,

You don't have to implement the latter because POSIX API already provides it. You can use `getrlimit(2)` and `setrlimit(2)` with `RLIMIT_NOFILE`. In addition, the upper limit can be configured with `ulimit -n MAX`.

> I think OSH could give a better error message than other shells for such a program ("max user fd exceeded" rather than some other weird I/O error).

Since the POSIX provides the configurable limit, similar error messages (e.g. Too many open files) are output in Bash and other shells.

```bash
bash$ ulimit -n 20
bash$ for i in {1..20}; do exec {fd}>/dev/null; done
bash: redirection error: cannot duplicate fd: Too many open files
bash: /dev/null: Too many open files
bash: redirection error: cannot duplicate fd: Too many open files
bash: /dev/null: Too many open files
bash: redirection error: cannot duplicate fd: Too many open files
bash: /dev/null: Too many open files
```

**Comment by andychu** [comment]
The issue I see isn't strictly about `ulimit` -- it's that the user script can "find" the fd used by `source` and corrupt it.  There has to be **shell** fd open to implement `source`.

Actually I think your change even has that logic:

```
      new_fd = fcntl.fcntl(fd1, fcntl.F_DUPFD, 10)
```

https://github.com/oilshell/oil/blob/master/core/process.py#L244


Why did you put 10 there?  My understanding is because descriptors 0-9 are used by POSIX shell programs, and 10+ is used by the shell.

----

From `man fnctl`

```
   Duplicating a file descriptor
       F_DUPFD (int)
              Find the lowest numbered available file descriptor greater than or equal to arg and make it be a copy of fd.  This is different from dup2(2), which uses exactly the descriptor specified.

              On success, the new descriptor is returned.

              See dup(2) for further details.
```

I believe this semantic is a syscall **only for the shell** to separate user FDs and shell FDs.  Otherwise why would it exist?

-----

Let  me write some code to demonstrate, but this was my theory from learning about the `F_DUPFD` semantics awhile back (which I need to change Oil to consistently use, since there is some old cruft in there)

**Comment by andychu** [comment]
To clarify, the specific claim is that  any other program that needs to manipulate descriptors can just use `dup()`.

- I think `dup2()` was added for shells to implement stuff like `3>&1`
- But `dup2()` isn't sufficient to avoid collisions, so `fcntl(..., F_DUPFD)` was added.  Because the interpreter cannot predict what file descriptors the program will use.

```
   dup2()
       The dup2() system call performs the same task as dup(), but instead of using the lowest-numbered unused file descriptor, it uses the descriptor number specified in newfd.  If the descriptor newfd was previously  open,  it  is
       silently closed before being reused.
```

**Comment by akinomyoga** [comment]
Ah, I think now I understand your point. Thank you for the explanation!

> 1. max descriptor a shell script can mention explicitly, e.g. exec 99>& 1
> 2. max descriptor that {fd}< can use.
>
> Those are both easy to implement, and unlikely to break anything, so I think we should put them in.
>
> They can be relaxed later if there is any issue, but I'd rather start off stricter. It seems 9 is too strict but we can make it higher.

I now agree with this direction.

----

> To clarify, the specific claim is that any other program that needs to manipulate descriptors can just use dup() (or open()).

I'm afraid that in-process external libraries that use `dup()` or `open()` can get the file descriptors of 0-9. If a user opens the same file descriptor after that by `N>`, it will be a problem. ... Ah, OK. You are planning to rewrite the external libraries (such as `libevent` / `libev` / `libuv`) to use `fcntl` instead of naively using `dup` or `open`? Yes, I think we can avoid the problem by rewriting the libraries.

**Comment by andychu** [comment]
OK I added a *lexing* limit of 2 digits, and _SHELL_MIN_FD is now 100.

After testing other shells and looking at the code more, I'm confident this is necessary.  The shortcut is test case 48 here:

http://travis-ci.oilshell.org/jobs/2020-03-22__20-12-23.wwz/_tmp/spec/redirect.html

mksh has a max of 24, while dash and zsh has a max of 10. 

- They are also *lexing* limits  (1 digit)
- If you `strace -e fcntl,dup2`, you can see it in  every shell.  Descriptors get "saved" at _SHELL_MIN_FD or higher.

Another way of saying it is that you need an argument for `F_DUPFD` -- it has  to be larger than the maximum descriptor mentioned in a shell script, or the shell will be forced to do things to avoid getting corrupted, which is the thing mentioned aosabook in bash.

-----------

Anyway thanks for all the patches!  This was a huge help and I even felt comfortable making #223 non-essential.  I did some big refactoring and simplification, and it's great to have move, close, and named file descriptors before doing that.  I think the code is getting pretty clean and I would even feel comfortable rewriting it in C++, now that the structure is more understood.

If you want to talk about this issue more, let me know but I think there are lots of other things in ble.sh that are very interesting.  I don't think anything will be broken as descriptors up to 99 are allowed.

**Comment by akinomyoga** [comment]
> Again I believe that F_DUPFD is a special hook in the kernel for the shell and no other program (other programs can use dup, and I believe even dup2 is largely useless outside a shell)

Maybe I miss the background of this discussion, but I don't think so. I agree that normal applications will not use these system calls, but there is a type of programs that needs to manage file descriptors such as terminals. For example, terminals manage the file descriptors of PTY masters and slaves. The terminal needs to prepare 0, 1, and 2 for applications, for which `dup2(2)` is usually used to move file descriptors. For another example, SSH also needs to prepare 0-2 for shells. I think all programs which prepare 0-2 for other programs are likely to use `dup2(2)`. I don't know about the use case for `F_DUPFD` other than in shells, but I cannot conclude it is only for the shells just because I don't know the other cases. There are so many different types of programs...

> If you want to talk about this issue more, let me know

Thank you! I think this issue is now settled.

**Comment by andychu** [comment]
Yes terminals are a good point.

I did search with Debian code search and grep.app and I found many usages of F_DUPFD_CLOEXEC, although a lot of them are in wrapper libraries for various languages.  A lot of them pass the arg `3` so I guess they want to keep the descriptor out of the 0-2 range.  I don't think I found any use that didn't use `0` or `3` actually but I didn't look that deeply.

**Comment by andychu** [comment]
Fixed: http://www.oilshell.org/blog/2020/03/release-0.8.pre3.html
