### ISSUE TITLE
xtrace output doubles backslashes and single-quotes

### ISSUE THREAD

**Issue by Crestwave** [oilshell/oil#700]
I'm guessing this isn't intended because you can run a command from the xtrace output and get a completely different result; this tripped me up for quite a while when debugging for #679.

```bash
osh$ set -x
osh$ echo '\'
+ echo '\\'
\
```

**Comment by andychu** [comment]
OK, yeah I can change this to use some shell routines, e.g. for `%q` or something.  Right now it's using Python syntax with `repr()`!!

**Comment by andychu** [comment]
One thing I noticed is that for a string with new lines like

```
x=$'one\ntwo'
```

bash actually prints a real newline in the `set -x` format.  But it could use the `printf %q` or `${x@Q}` format which gives you back a string in the `$''` format.

mksh does that.

I'm not sure exactly what to do for OSH.    Right now we don't have a routine that outputs `$''` format.  I wanted to "standardize" around CSTR in #582, but that could also be confusing because the format uses `'\\'` for a single backslash.

If it were `$'\\'`  or `c'\\'` it could be less confusing.

**Comment by andychu** [comment]
Weird, bash does print non-printable characters with `$''` like `$'\003'`, but it doesn't print newlines like that.

So yeah the goal of CSTR in #582 is to come up with one format rather than 10 different little buggy formats that bash has.  There are similar issues when you try to complete filenames with newlines, etc.

**Comment by andychu** [comment]
OK I fixed this -- I wrote a proper shell string encoder!  It uses `''` properly, and it uses `$''` if it needs to use backslash escapes.

(I generalized this to QSN which is the new name for CSTR .. there is a thread on Zulip about it if anyone's interested.)
