### ISSUE TITLE
nocasematch shell option doesn't seem to work

### ISSUE THREAD

**Issue by Crestwave** [oilshell/oil#701]
Forgot to open this issue yesterday; required for #627.

```bash
$ shopt -s nocasematch
$ [[ a == A ]]; echo $?
0
$ [[ A == a ]]; echo $?
0
```

```bash
osh$ shopt -s nocasematch
osh$ [[ a == A ]]; echo $?
1
osh$ [[ A == a ]]; echo $?
1
```

**Comment by andychu** [comment]
This is similar to #610  I believe.  It's basically a flag on `fnmatch()` or `glob()`.

I stubbed out a lot of the bash options as no-ops to get past superficial errors.  So `shopt -s nocasematch` is a no-op now.  Not sure if we should make it stricter or not.


Those test cases would be great to copy into `spec/dbracket.test.sh` if you any cycles:

https://github.com/oilshell/oil/wiki/Spec-Tests

In any case thanks for testing, this is helpful.   I thought neofetch would be easier to run since it was bash 3.0 ... But it seems like it's within spitting distance.

**Comment by Crestwave** [comment]
What do you mean by "if you any cycles"?

> I thought neofetch would be easier to run since it was bash 3.0 ... But it seems like it's within spitting distance.

Definitely! I'm not sure if you saw it in the middle of all my babble in #679, but I was able to get a pretty good result with some temporary patches. After finding and patching the later issues I found, I can now get a [perfect 1:1 Neofetch output](https://i.imgur.com/pZt1lFS_d.png?maxwidth=9999&fidelty=high)!

**Comment by andychu** [comment]
This is great!  Can you share the patch?  I'm interested in how big it is.

-----

I meant that I could use help putting these bugs in the test cases with some pull requests.  That is the first step and is often 50% of the work.  I forget if you have done that before?  But it seems like you're one of the best equipped people to do that, i.e. you already are narrowing down the differences very precisely, which is hard for inexperienced shell users.

For example if you search for "failing" here you can see a bunch of commits that @akinomyoga and I added:

http://www.oilshell.org/release/0.8.pre3/changelog.html

https://github.com/oilshell/oil/commit/15ea657c4127262986674236b04b19fa2a0694f5

https://github.com/oilshell/oil/commit/5614b34a9ff89409eed561fb1dad43827313cce7

https://github.com/oilshell/oil/commit/3e4ef4001e37a970d1b54d00ac0da251fccbcbba

(the way I find which file to add them do is: `grep FOO spec/*.test.sh`

Any spec tests that reveal a difference between Oil and other shells are accepted, even if we don't actually fix them.  (But we almost always will if a real program relies on the behavior, although it's a question of priorities.)

----

Off the top my head:

- `nocasematch` can use one (this is likely to be bash only?)
- I think #702 although I didn't look at the details.  Probably goes in one of the `spec/var-sub-*` files.
- #699 -- traps are in an immature state, but I do recall them varying between shells

I already added them for `$_` and the `xtrace` output.

----

Anyway it's encouraging we're getting close to running neofetch.  That's definite motivation for knocking off the rest of these issues.

Although I want to do a "word eval / split / glob overhaul" to fix many at once, and that may take awhile since it's a more fundamental change.

**Comment by andychu** [comment]
Also, the tests are published with every commit now, and I think it's kind of fun to see the numbers go up and down :)

http://travis-ci.oilshell.org/jobs/2020-04-07__20-22-13.wwz/_tmp/spec/osh.html

**Comment by Crestwave** [comment]
> This is great! Can you share the patch? I'm interested in how big it is. 

Not too big, actually, now that you've fixed several of the issues: https://github.com/Crestwave/snippets/blob/master/neofetch.patch.

> I forget if you have done that before?

Nope; I figured it would do just as much good as the mini-tests I include in these issues. But I'll check it out.

**Comment by andychu** [comment]
Yeah you're basically already writing them, which is why I asked :)  However the spec tests clear up:

- the behavior of other shells.  We also consider non-bash shells.  For example I learned that zsh also implements `$_`, and I learned about a few differences between zsh and bash there.
  -  And I also learned that mksh and zsh implement `$(<file)`, and zsh does something different there too.
- The exact version of bash (right now we have a bash 4.4 binary, but we can upgrade whenever, as I just did for dash).  This seems to matter for quite a few tests.  

Feel free to ping me on Zulip if you have problems.  A few other people have done it so it should be in pretty good condition.  The first step is to run  `test/spec.sh smoke` and see if that works on your machine.  That runs the cases in `spec/smoke.test.sh`.

https://github.com/oilshell/oil/wiki/Spec-Tests

**Comment by BharathSatheeshKumar** [comment]
Try to parse and run ble.sh #653

**Comment by andychu** [comment]
Just noticed that Nix uses nocasematch

https://github.com/NixOS/nixpkgs/blob/fc2bfe1cdc910104e6df52c5dc449e8f855c66b7/pkgs/stdenv/generic/setup.sh#L987

from https://lobste.rs/s/eru89e/some_notes_on_using_nix#c_ssszkf

**Comment by akinomyoga** [comment]
Just to add, ble.sh also uses `nocasematch` to implement [the case-insensitive history search](https://github.com/akinomyoga/ble.sh/blob/1b15b851c7f7a576bac5390ecc2976ea02c58a38/src/history.sh#L2240).

**Comment by andychu** [comment]
Fixed last year, late announcment - https://www.oilshell.org/blog/2024/01/release-0.19.0.html  !
