### ISSUE TITLE
Implement DEBUG trap (hard to Ctrl-C out of ble.sh tests)

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#734]
I noticed this with

```
osh --rcfile oshrc.test-util
```

https://github.com/oilshell/oil/wiki/Running-ble.sh-With-Oil

@akinomyoga have you noticed this?  It's hard to cancel the tests when they're taking a long time?

I think you can cancel it fine in bash.  I rememeber shells might have a rule for this, especially interactively, but I don't remember exactly what it is.

**Comment by andychu** [comment]
FWIW this was my output at the end:

```
[section] util: 657/724 (67 fail, 0 crash, 0 skip)
osh$ 
```

Which seems pretty decent!

**Comment by akinomyoga** [comment]
> @akinomyoga have you noticed this?

Thank you for testing! I haven't noticed it. It works in Bash. It doesn't work in non-interactive sessions of Oil either.

I found that this is actually caused by missing support of the `DEBUG` trap  #619 in Oil. `ble.sh` sets its own trap handler for `INT` to handle it by itself (or otherwise, the entire processing of `ble.sh` would be killed by <kbd>C-c</kbd>). When `ble.sh` detects `INT`, it uses the `DEBUG` trap to cancel the corresponding execution. There is nothing wrong with Oil's handling of <kbd>C-c</kbd>.

**Comment by andychu** [comment]
Oh I see!  I have never used the DEBUG trap, but it executes before every SimpleCommand, which makes sense...

Closing this in favor of that issue.  Thanks for the diagnosis!
