### ISSUE TITLE
remove 'pass' builtin

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#735]
https://oilshell.zulipchat.com/#narrow/stream/121540-oil-discuss/topic/pass.20password.20manager

**Comment by grahamc** [comment]
The context in that thread is that `pass` is a builtin to Oil, and that Oil is not going for drop-in replacement status, but instead trying to be compatible with other shells without `if OSH...` statements. The thread includes an example of bash adding the `time` builtin, mirroring the `time` executable. The argument is shell scripts can replace calls to `pass` with `command pass` and get working behavior in Oil without breaking compatibility with Bash, Zsh, etc, since `command` is a universal builtin of "run this program". Some of the counter-discussion in the thread is that `time` is specified by POSIX and `pass` is not.

Anyway, I found this issue by this surprising parse on 981d0a26cd791243c4904e690afee862b6afbf6a:

```
$ cat example
pass foobar | mything --name="hello"

$ ./bin/osh ./example
  pass foobar | mything --name="hello"
                              ^
./example:1: Syntax error in expression (near Id.Arith_Equal)
```

After seeing this ticket I went looking for docs on what the `pass` builtin does and didn't find it after looking:

- https://www.oilshell.org/release/0.8.pre2/doc/known-differences.html#oil-has-more-builtins-which-shadow-external-commands
- https://www.oilshell.org/release/latest/doc/oil-builtins.html
- https://www.oilshell.org/release/latest/doc/io-builtins.html
- and:
```
oil$ help pass
  help pass
       ^~~~
[ interactive ]:4: no help topics match 'pass'
  help pass
  ^~~~
[ interactive ]:4: fatal: Exiting with status 1 (command in PID 9635)
```

and I'm actually still not sure what it does :).

**Comment by andychu** [comment]
Thanks for the report!  As mentioned on Zulip, I'm removing this ...

The  `_ EXPRESSION` syntax will suffice for this.

BTW, `pass` was for left to right evaluation, like

    pass x => upper() => strip('\n') => var y

I think there are some use cases for that, but it's probably far in the future anyway.

It relates a bit to dplyr, explained in this blog post: https://www.oilshell.org/blog/2018/11/30.html

**Comment by andychu** [comment]
This is done and will be out with the next release!

**Comment by andychu** [comment]
https://www.oilshell.org/release/0.8.3/
