### ISSUE TITLE
C++ rewrite vs Nim

### ISSUE THREAD

**Issue by tobimensch** [oilshell/oil#740]
Hey,

I'm generally interested in shells and programming languages,
read the oil FAQ, and some of your comments on porting to C++.

I feel it's my time to point out that porting the Python code to Nim,
would be a more natural path than porting it to C++.

Because Nim targets C/C++ itself, and speed is at the top of Nim
developers priorities, you'll get all the same performance benefits,
that you'd get from a C++ port.

Nim is pretty close to Python in Syntax and there's also some overlap
in features, and as someone who now has experience with Nim,
Python and C++ I feel confident that a port from Python to Nim would
pay off in the long run.

**Comment by andychu** [comment]
Yes I did mention Nim here:

http://www.oilshell.org/blog/2020/01/blog-roadmap.html#backup-plans

The main issue I had with it is that the generated code wasn't readable.  I care about and have been using the following tools:

- ASAN stack traces
- uftrace, not on the blog, but mentioned here: https://news.ycombinator.com/item?id=22089814  
- GDB.  I'm stepping through readable C++ source now, and that is essential.   Distro maintainers will have to do it too.  And Python pretty-printing plugins based on Oil's structures are also critical: https://github.com/oilshell/oil/blob/master/devtools/oil_gdb.py

I think that would be complicated by Nim's code gen, but I only tried it a little bit.

(BTW I tried Vala for the same reason -- it compiles to C.)

----

However if you or anyone else wants to investigate a Nim alternative, I'm open to it.

At the bottom of every release page I publish source code in DSLs that can be translated to other langauges, as a leg up or "head start" (i.e. not implementing Oil from scratch)

http://www.oilshell.org/release/latest/ (scroll down to "Source Code")

But the C++ translation is making a lot of progress now, so that's what I"ll be doing for the forseeable future.  The source language will remain Python/ASDL/re2c for the foreseeable future.

----

I did read about py2nim and remember being impressed, but I don't remember the details.  e.g.

https://www.reddit.com/r/nim/comments/aillno/speeding_up_python_with_nim/

**Comment by tobimensch** [comment]
> The main issue I had with it is that the generated code wasn't readable. I care about and have been using the following tools

Nim is using C/C++/(maybe WASM in the future) purely as compile target, there's no intention of generating idiomatic C code. When you're looking at Nim's C code you're looking at Nim's alternative to LLVM IR. (When Nim was started, there was no LLVM IR)

This doesn't mean you can't use GDB, valgrind or any of the other C/C++ tooling for Nim. There're GDB pretty printers for Nim, and the tooling will get better over time. You don't need to look at the C code, because Nim has very good error messages and you'll step through the actual Nim code with the GDB tooling.

Dismissing all the other benefits of Nim, because you felt that debugging could be harder without ever having spent a lot of time verifying that it actually is, means you've robbed yourself of an opportunity to learn one of the greatest programming languages in existence.

I've done my share of C/C++ projects, and I highly recommend you to not look at Nim as a toy, I've dug deep into Nim and I can get so much more done with it, with code that is by far more elegant. Nim macros are extremely powerful, and I'm sure will come in handy when programming a shell. There's nothing like it for C/C++ or Python.

Don't think of Nim as a way of speeding up Python either, because that's misleading and sells Nim short. Nim is a system's programming language just like C++ or rust.

**Comment by andychu** [comment]
OK well there's not really any point to this if you only want to talk about what other people should do vs. what you yourself could do.

If you can point to 30K+ lines of Nim code you've written and has a lot of users and deployments, that would be a lot more interesting than general reassurances and promises.  (It still wouldn't make a difference for the current work Oil, but it could make a difference for anyone else who wants to use Nim, which I encourage as mentioned.)

**Comment by glyh** [comment]
I have no offence here but it seems nim works with GDB. https://internet-of-tomohiro.netlify.app/nim/gdb.en.html

If there's any interest porting oils to nim I would like to help.
