### ISSUE TITLE
Incorrect fnmatch due to extended glob syntax

### ISSUE THREAD

**Issue by andychu** [oilshell/oil#758]
Does not match the pattern with parentheses.

```sh
$ ~/git/oil/bin/osh -c 'case "foo()" in *\(\)) echo "should be match"; esac'
```

```
$ dash -c 'case "foo()" in *\(\)) echo "should be match"; esac'
should be match
```

_Originally posted by @ko1nksm in https://github.com/oilshell/oil/issues/752#issuecomment-631125484_

**Comment by andychu** [comment]
Released: http://www.oilshell.org/blog/2020/05/translation-progress.html

**Comment by abathur** [comment]
When I was updating to 0.8.7, I also noticed a new test break that appears to be introduced with the tests in 61675c2 and not resolved by the fix in ee59db8. I assume, since I don't see other threads, that this is just on macOS (but haven't tried this on linux). Mainly mentioning it for searchability later :)

```
======================================================================
FAIL: testFnmatchExtglob (__main__.LibcTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "native/libc_test.py", line 110, in testFnmatchExtglob
    (pat, s, actual, expected))
AssertionError: Matching --@(help|verbose) against --verbose: got 0 but expected 1

----------------------------------------------------------------------
```

There ended up being [several of these tests to patch out](https://github.com/abathur/resholve/blob/master/0006_disable_failing_libc_tests.patch)

**Comment by andychu** [comment]
Thanks for the report, this is actually #612 which is still open

**Comment by abathur** [comment]
Aha :) 

Want me to delete the comment here and repost there? I landed here because I manually ~bisected the breaks to starting at 61675c2 and it pointed back here.
