### ISSUE TITLE
Why build oil on legacy Python?

### ISSUE THREAD

**Issue by cclauss** [oilshell/oil#79]
Why focus on Python2?

If a version of Python is going to be shipped in the shell then why pick [legacy Python that only has a two year lifespan](https://pythonclock.org/)?  Can’t we port oil to modern Python and drop the legacy baggage?

**Comment by andychu** [comment]
Python is for prototyping only -- as mentioned here, I'll publish this in a FAQ:

https://news.ycombinator.com/item?id=16277358

https://news.ycombinator.com/item?id=16277734

**Comment by somasis** [comment]
Out of curiosity, does that mean that it'll eventually be rewritten in something else (i.e. completely in C), or is it just that the stripped down interpreter will be integrated into the codebase? I figured the latter after reading the FAQ and some posts about the implementation, but I suppose I'm interested in a definite answer.

**Comment by andychu** [comment]
The stripped down interpreter is already there:

https://github.com/oilshell/oil/tree/master/Python-2.7.13

Try building the latest release tarball -- it will build (part of) Python 2 from that code.

And see http://www.oilshell.org/blog/2017/05/05.html

I definitely want to avoid rewriting it by hand in another language, C or otherwise, simply because that's a lot of work.  But, it's too slow to keep in Python, and there are a few other issues regarding signals and such.

These posts are a little old but also largely accurate:

http://www.oilshell.org/blog/tags.html?tag=OVM#OVM

Unfortunately I haven't done much work on the VM since those posts were written.  Now that OSH is more complete, I might try to strip some more code out.  That won't make it faster, but it might make it easier to modify.

**Comment by somasis** [comment]
Ah, okay, I hadn't seen that article about CPython being the starting point. "Prototyping" gave the impression that a rewrite in another language entirely was the plan. Thanks for explaining, I'm mostly curious from an embedded standpoint.

**Comment by andychu** [comment]
Oh and my best thinking now is that I can compile the Python code via the compiler in `opy/` to some leaner / faster VM / bytecode.  Oil uses a pretty small portion of Python -- no decorators, no classmethods, single inheritance, a pretty small part of the stdlib, etc.

It's either that or keep stripping down and forking the CPython interpreter.

I haven't done much work on either of those things, so I haven't written about them.  There are some intermediate steps that I might publish, like:

- Get rid of stuff that's not used at all, but still linked, like `complexobject.c`
- Get rid of the dependency on Python's re module.  This will benefit either strategy.
- Get rid of `posixmodule.c` -- adapt/rewrite only what the shell needs from libc.
- Get rid of `unicodeobject.c` -- use utf-8 routines and not unicode objects.

All those are small steps that will move it closer to C, and then I can think about if I want to make my own VM, or if I want to try to reuse more of CPython.  It depends on speed, memory usage, and a few other things.

**Comment by andychu** [comment]
Oh yes I want it to work on embedded systems, but it's not close to that yet.  Every release announcement says "it's too big and too slow" to acknowledge this.

I used to work on toybox (from the busybox maintainer, somewhat used on Android) and I'm lurking on the busybox mailing list and following what they do with ash.

OSH is only 16K lines of Python code, as opposed to 160K lines of C code in bash, so there is definitely a focus on making things small.  However it's small in the logical sense, which will hopefully translate to small in the actual code generated sense!!!  Somehow it will get there, but it will probably take the better part of a year, or more.


I'm defini

**Comment by somasis** [comment]
>I used to work on toybox (from the busybox maintainer, somewhat used on Android) and I'm lurking on the busybox mailing list and following what they do with ash.

hah, I could have swore I recognized your name from somewhere; I've been watching Toybox development for almost two years now. Glad to hear small systems are goal.

**Comment by cclauss** [comment]
Your __stripped down Python__ sounds a lot like the [RPython that Pypy is based on](http://rpython.readthedocs.io) or for speed, [look at Pypy itself](http://pypy.org) or [Cython](https://github.com/cython/cython)?

My bet is that you could pop out Python and pop in Pypy with little to no work and get nice performance gains.

**Comment by andychu** [comment]
That's also a FAQ, and PyPy is worse for OSH in both speed and memory usage:

https://github.com/oilshell/oil/blob/master/benchmarks/pypy.sh

**Comment by con-f-use** [comment]
@andychu , So in nixpkgs (issue 479927) we have the problem that [resholve](https://github.com/nixos/nixpkgs/blob/master/pkgs/development/misc/resholve/README.md) which uses the python2 oil parser is the only holdout of python2 left. What advice do you have for people who need to parse shell code from python, but can't use a sunset, unmaintained and therefore insecure version of Python?

**Comment by andychu** [comment]
Ah we talked about this on Zulip -- I think the best advice is to **upstream** `resholve` into `osh --tool resholve`

Then it will be **pure C++**, and will not have a Python dependency

**Comment by andychu** [comment]
That was discussed here - [#oils-dev > OPy replacing Python 2 in the build dependencies?](https://oilshell.zulipchat.com/#narrow/channel/121539-oils-dev/topic/OPy.20replacing.20Python.202.20in.20the.20build.20dependencies.3F/with/569550863)

Happy to discuss more

(actually if someone has time available, I think this would be an ideal project for an NLnet application ... since NLnet funds Nix as well ... we could talk about that)

**Comment by con-f-use** [comment]
⬆️  @abathur

Personally, I think python3 bindings for the parser would be valuable outside of resholve, too. Xonsh for instance was originally build on the oil parser, at least it was back when I worked with it.
