### ISSUE TITLE
Don't require `sudo` for `build/dev.sh ubuntu-deps`

### ISSUE THREAD

**Issue by jyn514** [oilshell/oil#791]
Random scripts requiring sudo is my pet peeve :P Especially since it gives no indication of what command is actually being run. The two options I see are

1. `set -v` (or `set -x`) for ubuntu-deps, so you see the command. This is not ideal but still much better than blindly running sudo.
2. Removing `ubuntu-deps` and putting those lines in the contributing guide directly so the user has to copy/paste them.

```
$ build/dev.sh ubuntu-deps
[sudo] password for joshua: 
```

**Comment by andychu** [comment]
Yeah it's not my favorite either.  I think having the lines in source control is a good idea, so maybe `set -x` for now ?

Long term / pipe dream: what would be nice if you could pass the *capability* to run `apt` as root, but not anything else as root!  (e.g. `rm`)  So the user would get some assurance that way

**Comment by jyn514** [comment]
Sounds good to me. Unfortunately shell doesn't have many options here.

> what would be nice if you could pass the capability to run apt as root, but not anything else as root! (e.g. rm) 

That sounds really cool! Are you interested in having that in oil/osh?

**Comment by andychu** [comment]
Yes, although now that I think about it, doing it at the shell level has some fundamental limitations, because processes can start other processes.  For example, OSH can start `find` or `xargs` which can start `sudo`.  Or OSH can start `sh`, etc.

The kernel has better knowledge of it.

----

This is sort of related to #588 .  I can imagine some mechanism like:

myhook.sh:

```
command_hook() {
  if test $1 = sudo; then
    die "I don't want to run this"
  fi
}

trap command_hook COMMAND   # like EXIT or DEBUG
```

invocation:

```
osh --source myhook.sh install-script.sh   # now it will fail on sudo
```

But yeah as mentioned that idea has some fundamental limitations.  I think you need containers to work around it, e.g. disallowing a subprocess like `find` or `xargs` to fork with `seccomp`.  That is possible but Linux-specific, so it's significant work.

Such a hook could still be useful in other ways though.

**Comment by abathur** [comment]
I guess everyone's trying to bolt transparency on post-hoc.

There's an idiom used by the multi-user/daemon Nix installer. I gather it used to ask the user's permission (with context/explanation) each time it needed to sudo (prompting might practical in the context here) but it was getting out of hand, so they moved over to prompting once, but also explicitly calling out every sudo invocation. Here's a screenshot I found on tecmint of how this looks: ![this screenshot](https://www.tecmint.com/wp-content/uploads/2018/11/Nix-Installation-Continues.png)

Unless the user has configured it to nag them for a password on every sudo, I think there's no way around the fact that (as I imagine most people have it configured) a malicious script could make an obviously-innocuous sudo request first, and then run nefarious follow-up commands before the user will get prompted again.

**Comment by andychu** [comment]
It looks liek this now, so at least it tells you what it's about to do... We could revisit this more later if necessary

```
$ build/dev.sh ubuntu-deps 
+ sudo apt install python-dev gawk libreadline-dev cmake
[sudo] password for andy: 
```

**Comment by jyn514** [comment]
Sounds good to me 👍
