### ISSUE TITLE
Bare double dash support

### ISSUE THREAD

**Issue by timetoplatypus** [oilshell/oil#86]
From https://unix.stackexchange.com/questions/11376/what-does-double-dash-mean-also-known-as-bare-double-dash#11382

> a double dash (--) is used in bash built-in commands and many other commands to signify the end of command options, after which only positional parameters are accepted.

Individual binaries implement this behavior sometimes but OSH as a shell also has to support it too in order for builtins to properly work. For example, using `touch -- -r` while in OSH works, however `cd --` does not ("No such file or directory" error).

I was going to write some spec tests for this but I've only ever written them for specific features. I'm not really sure how to write a spec test for whether the OSH interpreter is parsing user input correctly, if that makes sense. If there isn't a way to do this, I can just write the spec tests for every builtin OSH currently has.

**Comment by andychu** [comment]
Yes, good point.  After looking into this a tiny bit with the `read` builtin, I think the issue is that `cd` doesn't use `Parse()`.  It doesn't respect any flags right now.

https://github.com/oilshell/oil/blob/master/core/builtin.py#L488

I think `dirs` works because it calls `Parse()`   Compare these two:

    dirs -v
    dirs -- -v   # -v is an argument, not a flag, and ignored.

That actually works in OSH, although it might sort of be an accident?  Not sure.

Anyway, as far as I know, most builtins have flags (except `echo` flags need to be processed in a very particular way).  If they have flags, then they will use, `core/args.py`, and things should work, **I think**.

So maybe you could add stubs for `cd -L` and `-H` and all that.  I've honestly never used those and have no idea if they're useful.  You can just raise NotImplementedError if you get them.

And then I **think** that will fix the `--` problem for cd in a consistent way.  If cd is following the style of other builtins, there's probably no need to write tests for every builtin.  It should be solved in one place (with an exception for `echo` and maybe some others.)

**Comment by BatmanAoD** [comment]
Actually, it appears that as it's currently implemented, `pwd` isn't equivalent to  `$PWD` in `osh`, so the above doesn't work even after modifying `cd`. I'll open a separate issue about that.
