### ISSUE TITLE
Eggex library in Python

### ISSUE THREAD

**Issue by jtrakk** [oilshell/oil#869]
I'm interested in trying out eggexes in my Python code. Is it possible to simply use eggex as a Python library, instead of `re`? Could it be packaged for PyPI?

**Comment by andychu** [comment]
I would like that to happen, but it's not really part of the Oil project.  Eggex is a language that can have multiple implementations, just like regex can have multiple implementations.

Forking / extracting / minimizing the code is definitely possible and encouraged for something like this.

There are a few ways to do this -- #488  is one of them, e.g. translate eggex to Python's `re` syntax, instead of ERE.

Or it is possible to use ERE from Python with a C binding, which Oil has already.
